module.exports = {
    GET_LIST: 'DashBoard/ConcernStatusList',
    LOGIN: 'Login/List',
    GLOBAL_LOGIN: 'Login',
    REGISTER_DEVICE: 'RegisterDevice/RegisterDevice',
    GET_DEVICE_STATUS: 'RegisterDevice/DeviceStatus',
    DEVICE_STATUS: 'DeviceStatus',
    DASHBOARD_CONCERN_LIST: 'DashBoard/MainDashBoardList',
    CONCERN_LIST_FILTERED_BY_DATE: 'DashBoard/GetConcernByDates',
    DASHBOARD_CONCERN_COUNTS: 'DashBoard/GetConcernStatusCount',
    CATEGORY_LIST: 'Category/List',
    CUSTOMER_LIST: 'Customer/List',
    PRODUCT_LIST: 'Product/List',
    CREATE_PROJECT: 'Concerns/CreateProject',
    PROJECT_LIST: 'DeliverableInfo/ConcernProjectDetails',
    PROJECT_PERCENTAGE_UPDATE: 'PeriodicUpdate/Save',
    SUB_CATEGORY_LIST: 'SubCategory/List',
    PROBLEM_CLASSIFICATION_LIST: 'ProblemClassification/List',
    PRIORITY_LIST: 'Priority/List',
    DROPDOWN_LIST: 'DropDown/List',
    SAVE_NEW_ACTION_DESCRIPTION: 'PhaseAction/SaveActionDescription',
    SaveInterimAction: 'PhaseAction/SaveInterimAction',
    SaveRootCauseAction: 'PhaseAction/SaveRootCauseAction',
    SaveCorrectiveAction: 'PhaseAction/SaveCorrectiveAction',
    SavePermanentCorrectiveAction: 'PhaseAction/SavePermanentCorrectiveAction',
    SavePreventReocurranceAction: 'PhaseAction/SavePreventReocurranceAction',
    GET_EIGHTD_FORM_DATA: 'PhaseAction/Generate8DFormData',
    ADD_EIGHTD_FORM_ROW: 'PhaseAction/AddActionUsage8D',
    SAVE_EIGHTD_ATTACHMENT: 'PhaseAction/Save8DAttachments',
    FORM_INPUT_LIST: 'Concern/FormElementsGroup',
    SAVE_CONCERN: 'Concern/Save',
    SAVE_TEAM: 'Teams/SaveTeam',
    GET_CONCERN: 'Concern/GetConcern',
    DELETE_CONCERN: 'Concern/DeleteConcern',
    // UPDATE_CONCERN: 'Concern/UpdateConcernStatus',
    UPDATE_CONCERN: 'Concern/UpdateConcernStatusFromMobile',
    GET_ACTION_DESCRIPTION: 'PhaseAction/G8DActionDescription',
    GET_CUSTOM_DROPDOWN: 'DropDown/GetCustomDropDown',
    GET_CUSTOM_RADIOBUTTON: 'DropDown/GetRadioButton',
    GET_USERS: '/api/?results=5',
    GET_TEAM_LIST: 'Teams/List?',
    GET_TEAM_USERS: 'Teams/Users',
    GET_ESTIMATION_PICKER: 'Concern/ComponentElementsGroup?',
    GET_CUSTOMERS_PICKER: 'Concern/ComponentElementsGroup?',
    GET_CUSTOMERS_CONTACT_PERSONS: 'Customer/CustomerContactPersons',
    GET_CUSTOMERS_CONTACT_DETAILS: 'Customer/CustomerContactDetails',
    GET_CUSTOMERS_ADDRESS: 'Customer/CustomerAddressList',
    GET_SUPPLIERS_ADDRESS: 'Supplier/SupplierAddressList',
    GET_SUPPLIERS_CONTACT_PERSONS: 'Supplier/SupplierContactPersons',
    GET_SUPPLIERS_CONTACT_DETAILS: 'Supplier/SupplierContactDetails',
    GET_SQE_ENGINEER: 'Concern/SQEEngineerList',
    GET_SQE_MANAGER: 'Concern/SQEManagerList',
    GET_SUPPLIERS_PICKER: 'Concern/ComponentElementsGroup?',
    APPROVE_REJECT: 'PhaseAction/CARApproveReject',
    GET_CAR_VIEW_LOG: 'PhaseAction/GetCARViewLog',
    GET_PROBLEM_IMAGES: 'Concern/GetProblemImages',
    GET_OK_PICKER: 'Attachment/GetConcernDocuments',
    GET_NOT_OK_PICKER: 'Attachment/GetConcernDocuments',
    GET_ATTACHMENT_PICKER: 'Attachment/GetConcernDocuments',
    DELETE_PROBLEM_IMAGES: 'Concern/DeleteProblemImages',
    GET_PROBLEM_DESCRIPTION_ATTACHMENT: 'Attachment/GetConcernDocuments',
    DELETE_PROBLEM_DESCRIPTION_ATTACHMENT: 'Attachment/DeleteConcernDocuments',
    IC_LOGIN:'Login',
    IC_GET_IS:'GetInspectionSchedule',
    IC_SETTINGS:'GetICSettings',
    IC_FRQ_FORM:'GetFrequency',
    IC_RESPONSIBLE_PERSON:"GetLotCreation",
    IC_FORM_SUBMIT:"SaveICInspectionEntry",
    IC_SUPERVISOR_LIST:'SupervisorApprovalList',
    IC_GET_ATTACHEMENTS:'GetAttachment',
    IC_COMPLETED_LIST:'GetCompletedInspection',
    IC_OPERATOR_LIST:'GetOperatorWorksheet',
    IC_SINGLE_SYNC:'InsertSamples',
    IC_INPROCESS_SINGLE_SYNC:'InsertSamplesInpro',
    IC_GET_SEARCH_INSPECTIONLIST:'GetSearchInspectionList',
    IC_SEARCH_INSPECTION_DOWNLOAD:'SearchInspectionFormDownload',
    LOGIN_LOGO:'GetCompanyLogo',
    ICTABCOUNT:'IClistCount',
    IC_SUPERVISOR_DOWNLOAD:'GetSupervisorForm',
    IC_OPERATION_LIST:'GetOperations',
    IC_BULK_SYNC:'BulkSync',
};
