import { StyleSheet, Dimensions, Platform } from 'react-native';
import { width, height } from 'react-native-dimension';
import Fonts from '../Themes/Fonts';
import { COLORS, FONT_SIZE, SPACING } from 'constants/theme-constants';

let Window = Dimensions.get('window');

export const clauseMultiSelectStyles = {
    chipText: {
        maxWidth: Dimensions.get('screen').width - 90,
    },
    selectToggle: {
        paddingLeft: 0,
        paddingRight: 0,
    },
    selectToggleText: {
        marginLeft: 0,
    },
};

export const processMultiSelectStyles = {
    chipText: {
        maxWidth: Dimensions.get('screen').width - 90,
    },
    selectToggle: {
        paddingLeft: 0,
        paddingRight: 0,
    },
    selectToggleText: {
        marginLeft: 0,
    },
};

export default StyleSheet.create({
    wrapper: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'flex-start',
        backgroundColor: '#FFFFFF',
    },
    keyboardAwareContent: {
        flexGrow: 1,
    },
    formBottomSpacer: {
        marginBottom: 50,
    },
    hidden: {
        display: 'none',
    },
    flexOne: {
        flex: 1,
    },
    listMarginTopSmall: {
        marginTop: 10,
    },
    inputNoHorizontalPadding: {
        paddingHorizontal: 0,
        color: '#123C95',
    },
    inputContainerNoPad: {
        paddingHorizontal: 0,
        marginBottom: 0,
        marginLeft: 0,
    },
    placeholderTextMuted: {
        fontFamily: 'OpenSans-Regular',
        fontSize: FONT_SIZE.SMALL,
        width: '100%',
        color: COLORS.themeBlack,
        fontWeight: 'bold',
    },
    standardRequirementText: {
        color: '#A6A6A6',
        marginBottom: 4,
        fontSize: Fonts.size.regular,
        fontFamily: 'OpenSans-Regular',
    },
    attachmentImageLarge: {
        width: width(70),
        height: 200,
        resizeMode: 'cover',
        alignSelf: 'center',
    },
    attachmentIconContainer: {
        width: width(70),
        height: 200,
    },
    attachmentIconLarge: {
        flex: 1,
        alignSelf: 'center',
        marginTop: 70,
    },
    attachmentListItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        margin: 2,
        borderColor: '#2a4944',
        borderWidth: 1,
        height: '90%',
    },
    missingFileText: {
        left: 10,
        color: 'red',
        fontFamily: 'OpenSans-Regular',
    },
    columnFlex: {
        flexDirection: 'column',
    },
    filenameText: {
        fontFamily: 'OpenSans-Regular',
        alignSelf: 'center',
    },
    attachmentDeleteBtn: {
        width: '10%',
        right: 10,
        top: 10,
        position: 'absolute',
    },
    eyeRow: {
        position: 'relative',
        minHeight: 40,
        width: '100%',
    },
    eyeIcon: {
        position: 'absolute',
        right: 0,
        top: 20,
        padding: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    failureDropdownWrapper: {
        position: 'relative',
    },
    failureClearButton: {
        position: 'absolute',
        top: -10,
        right: 35,
        height: 20,
        width: 20,
        zIndex: 9,
        borderColor: '#A6A6A6',
    },
    failureClearIconWrapper: {
        backgroundColor: 'transparent',
        top: 18,
    },
    columnPadLeft: {
        paddingLeft: 0,
        flexDirection: 'column',
    },
    processLabel: {
        fontSize: FONT_SIZE.SMALL,
        width: '100%',
        color: COLORS.themeBlack,
        paddingBottom: 5,
        margin: 0,
        marginTop: 20,
        fontFamily: 'OpenSans-Bold',
        fontWeight: 'bold',
    },
    radioLabelStyle: {
        paddingRight: 12,
    },
    selectedIconStyle: {
        color: '#4caf50',
        paddingLeft: 10,
    },
    contentLoaderContainer: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        height: '100%',
    },
    contentLoaderTitle: {
        fontSize: Fonts.size.regular,
        fontFamily: 'OpenSans-Regular',
    },
    // Header styles
    header: {
        width: '100%',
        flexDirection: 'row',
        padding: 5,
        alignContent: 'center',
        justifyContent: 'space-around',
        height: 65,
        elevation: 4,
        shadowOffset: { width: 2, height: 10 },
        shadowColor: 'lightgrey',
        shadowOpacity: 0.5,
        shadowRadius: 4,
    },
    heading: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        width: '70%',
        height: 65,
    },
    headingText: {
        fontSize: Fonts.size.h6,
        color: '#000',
        textAlign: 'center',
        fontFamily: 'OpenSans-Bold',
    },
    backlogo: {
        flexDirection: 'row',
        backgroundColor: 'transparent',
        width: width(15),
        height: 65,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerDiv: {
        width: width(15),
        height: 65,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    rightHeader: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        right: 10,
        height: 80,
    },
    backgroundImage: {
        resizeMode: 'stretch',
        width: width(30),
        height: 80,
        zIndex: 0,
    },

    // Footer styles
    footer: {
        bottom: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        backgroundColor: '#FFFFFF',
        paddingVertical: 8,
        paddingHorizontal: 10,
        minHeight: 76,
        zIndex: 3000,
    },
    footerAdjusted: {
        height: 100,
        paddingBottom: Platform.OS === 'ios' ? 8 : 6,
    },
    footerDiv: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        // shadowOffset: {width: 2, height: 10},
        // shadowColor: 'lightgrey',
        // shadowOpacity: 0.5,
        // shadowRadius: 4,
    },
    footerDivAdjusted: {
        width: '100%',
        height: 100,
        paddingHorizontal: 10,
    },
    footerResponsiveWrap: {
        alignSelf: 'center',
        width: '100%',
    },
    footerLoader: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    footerTextContent: {
        color: 'white',
        fontSize: Fonts.size.regular,
    },
    footerDivContent: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    separatorSection: {
        flexDirection: 'column',
        alignItems: 'center',
        width: width(1),
        height: 140,
        backgroundColor: 'transparent',
        marginTop: 10,
    },

    inputSecond: {
        backgroundColor: 'transparent',
        width: '90%',
        left: 10,
        marginTop: 10,
    },
    inputAttach: {
        flexDirection: 'row',
        // top:1,
        marginLeft: 10,
    },

    boxCard1: {
        // position:'absolute',
        width: Window.width,
        height: height(9),
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },
    boxCard2: {
        width: Window.width,
        height: height(9),
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardL: {
        width: width(98),
        height: height(9),
        backgroundColor: 'white',
        borderRadius: 1,
        borderLeftWidth: 4,
        borderLeftColor: '#C1EAFC',
        elevation: 10,
        marginTop: 5,
    },
    card0L: {
        width: width(90),
        height: height(9),
        backgroundColor: '#D6D3D3',
        borderRadius: 1,
        borderLeftWidth: 4,
        borderLeftColor: '#C1EAFC',
        elevation: 10,
        marginTop: 5,
    },
    cardL1: {
        width: width(90),
        height: height(9),
        backgroundColor: 'white',
        borderRadius: 1,
        borderLeftWidth: 4,
        borderLeftColor: '#DFFFEF',
        elevation: 10,
        marginTop: 5,
    },
    cardL01: {
        width: width(90),
        height: height(9),
        backgroundColor: '#D6D3D3',
        borderRadius: 5,
        borderLeftWidth: 10,
        borderLeftColor: '#DFFFEF',
        elevation: 10,
    },
    input1: {
        backgroundColor: 'transparent',
        width: '90%',
        top: height(3),
    },
    placeholderT1: {
        fontSize: Fonts.size.regular,
        borderBottomColor: 'lightgrey',
        borderBottomWidth: 0.5,
        fontFamily: 'OpenSans-Regular',
        color: '#000',
    },
    placeholderT1Label: {
        fontSize: Fonts.size.regular,
        paddingTop: 5,
        borderBottomColor: 'lightgrey',
        borderBottomWidth: 0.5,
        width: '100%',
        paddingVertical: Platform.OS === 'ios' ? 5 : null,
        fontFamily: 'OpenSans-Regular',
        color: '#000',
    },
    placeholderSR: {
        fontSize: Fonts.size.regular,
        // width: '50%',
        fontFamily: 'OpenSans-Regular',
        color: '#000',
    },
    placeholderSRLabel: {
        fontSize: Fonts.size.regular,
        paddingTop: 5,
        width: '85%',
        fontFamily: 'OpenSans-Regular',
        paddingVertical: Platform.OS === 'ios' ? 55 : null,
        color: '#000',
    },

    input2: {
        backgroundColor: 'transparent',
        width: '90%',
        left: 10,
        marginTop: 10,
    },
    optionSec: {
        position: 'absolute',
        flexDirection: 'column',
        right: 0,
        top: height(4),
    },
    body: {
        position: 'absolute',
        width: Window.width,
        height: '80%',
        backgroundColor: 'transparent',
        top: height(11),
        justifyContent: 'center',
        alignItems: 'center',
        borderTopWidth: 0.5,
    },
    cardDiv: {
        width: width(90),
        height: '90%',
        backgroundColor: 'white',
        elevation: 10,
    },
    cardDiv3: {
        width: '90%',
        height: '85%',
        backgroundColor: 'white',
        elevation: 20,
    },
    viewOption: {
        // justifyContent:'center',
        // alignItems:'center',
        width: '100%',
        height: height(4.5),
        backgroundColor: 'transparent',
        bottom: 10,
    },
    optionBox: {
        width: width(20),
        height: height(4.5),
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: width(70),
    },
    ModalBox: {
        width: '92%',
        maxWidth: 900,
        maxHeight: '82%',
        minHeight: 260,
        backgroundColor: 'white',
        borderRadius: 10,
        flexDirection: 'column',
        overflow: 'hidden',
        alignSelf: 'center',
    },
    ModalBoxTablet: {
        width: '86%',
        maxWidth: 980,
        maxHeight: '84%',
    },
    ModalBoxLandscape: {
        width: '82%',
        maxWidth: 1100,
    },
    modalheader: {
        width: '100%',
        minHeight: 56,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        borderBottomWidth: 0.5,
        borderBottomColor: 'lightgrey',
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    modalbody: {
        width: '100%',
        flex: 1,
        backgroundColor: 'white',
        paddingHorizontal: 20,
        paddingTop: 16,
    },
    modalbodyContent: {
        paddingBottom: 12,
    },
    modalfooter: {
        width: '100%',
        minHeight: 56,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        borderTopWidth: 0.5,
        borderTopColor: 'lightgrey',
        paddingVertical: 12,
    },
    inputhigh: {
        backgroundColor: 'transparent',
        width: '100%',
        // paddingLeft:3,
        // backgroundColor:'red'
        // height:'80%',
        // left:5,
        // marginBottom:40,
        // marginTop:20
    },
    div01: {
        width: '100%',
        // height:height(10),
        backgroundColor: 'transparent',
        // marginTop:10,
        // alignItems:'center',
        // justifyContent:'center',
        flexDirection: 'row',
        paddingTop: 5,
    },
    div1: {
        width: '100%',
        //height:height(10),
        backgroundColor: 'transparent',
        marginTop: 20,
        // alignItems:'center',
        // justifyContent:'center',
        flexDirection: 'row',
        // backgroundColor:'yellow'
    },
    firstInputRow: {
        marginTop: 0,
    },
    div2: {
        width: '100%',
        // height:height(10),
        backgroundColor: 'transparent',
        // marginTop:10,
        // alignItems:'center',
        // justifyContent:'center',
        flexDirection: 'row',
        //marginBottom:30
        //backgroundColor:'red'
    },

    check: {
        position: 'absolute',
        // height:'0%',
        width: '10%',
        backgroundColor: 'transparent',
        // backgroundColor:'grey',
        right: 0,
    },
    input01: {
        backgroundColor: 'transparent',
        width: '90%',
        height: '80%',
    },
    input001: {
        backgroundColor: 'transparent',
        width: '90%',
        height: '90%',
        paddingLeft: 4,
    },
    input002: {
        backgroundColor: 'transparent',
        width: '100%',
        height: '90%',
    },
    placeholderT: {
        fontSize: Fonts.size.regular,
        width: '90%',
    },
    input02: {
        backgroundColor: 'transparent',
        width: '100%',
        marginTop: 10,
        paddingVertical: Platform.OS === 'ios' ? 10 : null,
    },
    standardRequirementInputText: {
        paddingRight: 42,
    },
    input03: {
        backgroundColor: 'transparent',
        width: '100%',
        height: '80%',
        paddingLeft: 0,
    },
    input04: {
        backgroundColor: 'transparent',
        width: '100%',
        height: '80%',
        paddingLeft: 0,
    },
    input05: {
        backgroundColor: 'transparent',
        width: '100%',
        height: '80%',
        paddingLeft: 0,
    },
    input06: {
        backgroundColor: 'yellow',
        width: '50%',
        height: '80%',
        flexDirection: 'row',
    },
    input07: {
        backgroundColor: 'transparent',
        width: '100%',
        height: '80%',
        paddingLeft: 0,
    },
    uploadButton: {
        backgroundColor: 'transparent',
        width: '50%',
        height: '80%',
        paddingLeft: 7,
        flexDirection: 'row',
    },

    // Body styles
    auditPageBody: {
        flex: 1,
        zIndex: 10,
        marginLeft: 0,
        marginRight: 0,
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: 'white',
        justifyContent: 'center',
        paddingBottom: 0,
        marginBottom: 0,
        alignSelf: 'stretch',
    },
    auditPageBodyResponsive: {
        alignSelf: 'center',
        width: '100%',
    },
    formSection: {
        width: '100%',
        marginBottom: 5,
    },
    formSection1: {
        width: '100%',
        marginBottom: 16,
    },
    fieldLabel: {
        fontSize: Fonts.size.regular,
        fontFamily: 'OpenSans-SemiBold',
        color: '#4A4A4A',
        marginBottom: 6,
        marginLeft: 0,
    },
    floatingDiv: {
        position: 'absolute',
        right: 20,
        bottom: 90,
        zIndex: 1000,
        justifyContent: 'center',
        alignItems: 'center',
    },
    floatinBtn: {
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
        width: 60,
        height: 60,
        // backgroundColor:'#00b3d6',
        borderRadius: 100,
        zIndex: 1000,
        elevation: 15,
    },
    footerButtonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: 6,
    },
    footerButtonWrapper: {
        flex: 1,
        minWidth: 0,
        marginHorizontal: 4,
    },
    footerButton: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 10,
        borderRadius: 8,
        backgroundColor: '#123C95',
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 2,
        elevation: 1,
        marginHorizontal: 0,
        width: '100%',
    },
    footerPrimaryButton: {
        height: 65,
        borderRadius: 18,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 4,
        elevation: 4,
    },
    footerPrimaryButtonGradient: {
        width: '100%',
        height: '100%',
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
    },
    footerPrimaryButtonTablet: {
        height: 72,
        borderRadius: 22,
    },
    footerPrimaryButtonGradientTablet: {
        borderRadius: 22,
    },
    footerButtonText: {
        color: 'white',
        fontSize: Fonts.size.medium,
        fontFamily: 'OpenSans-SemiBold',
        marginTop: 6,
    },
    footerButtonPrimary: {
        backgroundColor: '#123C95',
    },
    footerButtonSecondary: {
        backgroundColor: 'white',
        borderWidth: 1.2,
        borderColor: '#123C95',
    },
    footerVoiceButton: {
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#123C95',
    },
    footerVoiceButtonActive: {
        backgroundColor: '#123C95',
    },
    footerActionText: {
        color: '#ffffff',
        fontSize: 14,
        fontFamily: 'OpenSans-SemiBold',
        paddingTop: 5,
    },
    footerActionTextSecondary: {
        color: '#123C95',
    },
    pulseWrapper: {
        right: 70,
        position: 'absolute',
    },
    modalOuterBox: {
        backgroundColor: 'rgba(0,0,0,0.8)',
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        margin: 0,
        top: 0,
        left: 0,
    },
    modalHeaderTitle: {
        fontSize: Fonts.size.h5,
        fontFamily: 'OpenSans-Regular',
        color: '#000',
    },
    modalSection: {
        paddingBottom: 20,
    },
    modalSectionTitle: {
        fontSize: Fonts.size.regular,
        fontFamily: 'OpenSans-Bold',
        color: '#000',
    },
    modalContentText: {
        fontSize: Fonts.size.regular,
        fontFamily: 'OpenSans-Regular',
        color: '#000',
    },
    closeModalText: {
        fontSize: Fonts.size.regular,
        color: '#00a1e2',
        paddingVertical: 2,
        fontFamily: 'OpenSans-Regular',
    },
    modalEmptyText: {
        fontSize: Fonts.size.regular,
        color: '#6A6A6A',
        fontFamily: 'OpenSans-Regular',
    },
    sectionTop: {
        backgroundColor: 'white',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        borderBottomWidth: 0.5,
        borderBottomColor: '#C4C4C4',
        padding: 10,
    },
    sectionContent: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    boxContent: {
        width: '100%',
        color: 'black',
        fontSize: Fonts.size.mediump,
        textAlign: 'center',
        fontFamily: 'OpenSans-Regular',
    },
    sectionBtn: {
        backgroundColor: 'white',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        borderBottomWidth: 0.5,
        borderBottomColor: '#C4C4C4',
        padding: 10,
    },
    sectionTopCancel: {
        backgroundColor: 'white',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        padding: 10,
    },
    boxContentClose: {
        width: '100%',
        color: '#000',
        textAlign: 'center',
        fontSize: Fonts.size.mediump,
        fontFamily: 'OpenSans-Regular',
    },
    ncModal: {
        //flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        width: '90%',
        //height: '40%',
        backgroundColor: 'white',
        borderRadius: 10,
        margin: 10,
        padding: 10,
        elevation: 8,
        borderColor: 'lightgrey',
        borderWidth: 0.5,
    },
    modalheading: {
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: 'transparent',
        borderBottomColor: 'lightgrey',
        borderBottomWidth: 0.8,
        alignItems: 'center',
        padding: 20,
    },
    modalbodyReset: {
        width: '90%',
        height: 150,
        backgroundColor: 'white',
        borderRadius: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalCont: {
        width: '95%',
        height: 60,
        flexDirection: 'column',
        backgroundColor: 'transparent',
    },
    modalcont2: {
        width: '95%',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        height: 60,
        backgroundColor: 'transparent',
    },
    modalTouch: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '95%',
        height: 30,
        margin: 2,
        backgroundColor: 'transparent',
        borderWidth: 0.5,
        borderColor: 'lightgrey',
    },
    attachModal: {
        width: '100%',
        height: 50,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
    },
    attachModal1: {
        width: '100%',
        height: 50,
        backgroundColor: 'white',
        borderTopColor: 'lightgrey',
        borderTopWidth: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    attachModal2: {
        width: '100%',
        height: 50,
        backgroundColor: 'white',
        borderTopColor: 'lightgrey',
        borderTopWidth: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    attachModal3: {
        width: '100%',
        height: 50,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        borderTopColor: 'lightgrey',
        borderTopWidth: 1,
    },
    boxContentCam: {
        //width: '100%',
        color: '#485B9E',
        fontSize: Fonts.size.mediump,
        fontFamily: 'OpenSans-Regular',
        // textAlign: 'center',
        // paddingLeft: 20,
    },
    suggestionModal: {
        width: '90%',
        height: 200,
        backgroundColor: 'white',
        borderRadius: 5,
        padding: 10,
    },
    suggestionHeaderRow: {
        width: '100%',
        height: '25%',
        backgroundColor: 'white',
        marginTop: 10,
        borderBottomWidth: 1,
        borderBottomColor: 'lightgrey',
        flexDirection: 'row',
    },
    suggestionLoaderWrap: {
        width: '20%',
    },
    suggestionTitleWrap: {
        width: '80%',
        justifyContent: 'center',
        paddingLeft: '13%',
    },
    suggestionTitleText: {
        fontSize: 18,
        fontFamily: 'OpenSans-Regular',
    },
    suggestionbox: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#E6E6E6',
        borderRadius: 20,
        marginTop: 10,
        marginRight: 10,
        paddingHorizontal: 15,
        paddingVertical: 8,
    },
    suggestionItemText: {
        fontFamily: 'OpenSans-Regular',
    },
    footerShadowButton: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        paddingHorizontal: 10,
        borderRadius: 8,
        backgroundColor: '#123C95',
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 2,
        elevation: 1,
        margin: 10,
    },
});
