export const projectData = [
    {
      "ProjectID": "43",
      "ActionId": "430005",
      "Actions": "01_Adwaith",
      "Description": "Design FMEA",
      "ActionType": "Pending Deliverables",
      "site": "Corporate",
      "StartDate": "2022-07-29T09:00:00",
      "DueDate": "2022-08-01T13:15:00",
      "DueByDays": -268,
      "SiteId": 1,
      "IsNew": 1,
      "Percentage": 50,
      "Status": "Deadline violated",
      "ColorCode": "rgb(239, 65, 54)",
      "ProjectOwner": "Mark Augustin  , Admin Adwaith Industries , Anna Azhalle  ",
      "ResourcePercent": 100,
      "Modules": null,
      "User": "Jobi Thomas  ",
      "IsOutputMandatory": 0,
      "ProjectOwnerCheck": 0,
      "TaskOwner": "41[100%],107[100%]",
      "TaskOwnerCheck": 1
    },
    {
      "ProjectID": "43",
      "ActionId": "430011",
      "Actions": "01_Adwaith",
      "Description": "Material, Performance Test Results",
      "ActionType": "Pending Deliverables",
      "site": "Corporate",
      "StartDate": "2022-08-29T09:00:00",
      "DueDate": "2022-08-30T13:15:00",
      "DueByDays": -239,
      "SiteId": 1,
      "IsNew": 1,
      "Percentage": 0,
      "Status": "Deadline violated",
      "ColorCode": "rgb(239, 65, 54)",
      "ProjectOwner": "Mark Augustin  , Admin Adwaith Industries , Anna Azhalle  ",
      "ResourcePercent": 0,
      "Modules": null,
      "User": "Jobi Thomas  ",
      "IsOutputMandatory": 1,
      "ProjectOwnerCheck": 0,
      "TaskOwner": "42[100%],107[100%]",
      "TaskOwnerCheck": 1
    },
    {
      "ProjectID": "43",
      "ActionId": "430022",
      "Actions": "01_Adwaith",
      "Description": "PSW",
      "ActionType": "Pending Deliverables",
      "site": "Corporate",
      "StartDate": "2022-08-15T00:00:00",
      "DueDate": "2022-08-15T13:15:00",
      "DueByDays": -254,
      "SiteId": 1,
      "IsNew": 1,
      "Percentage": 50,
      "Status": "Deadline violated",
      "ColorCode": "rgb(239, 65, 54)",
      "ProjectOwner": "Mark Augustin  , Admin Adwaith Industries , Anna Azhalle  ",
      "ResourcePercent": 100,
      "Modules": null,
      "User": "Jobi Thomas  ",
      "IsOutputMandatory": 0,
      "ProjectOwnerCheck": 0,
      "TaskOwner": "41[100%],107[100%]",
      "TaskOwnerCheck": 1
    },
    {
      "ProjectID": "199",
      "ActionId": "1990014",
      "Actions": "Pillar Approval Check",
      "Description": "Pilot Plan",
      "ActionType": "Pending Deliverables",
      "site": "Corporate",
      "StartDate": "2023-04-11T09:00:00",
      "DueDate": "2023-04-11T13:15:00",
      "DueByDays": -15,
      "SiteId": 1,
      "IsNew": 1,
      "Percentage": 0,
      "Status": "Deadline violated",
      "ColorCode": "rgb(239, 65, 54)",
      "ProjectOwner": "Mark Augustin  ",
      "ResourcePercent": 0,
      "Modules": null,
      "User": "Jobi Thomas  ",
      "IsOutputMandatory": 1,
      "ProjectOwnerCheck": 0,
      "TaskOwner": "8,107",
      "TaskOwnerCheck": 1
    },
    {
      "ProjectID": "199",
      "ActionId": "1990016",
      "Actions": "Pillar Approval Check",
      "Description": "Cost Benefit Analysis",
      "ActionType": "Pending Deliverables",
      "site": "Corporate",
      "StartDate": "2023-04-11T09:00:00",
      "DueDate": "2023-04-11T17:30:00",
      "DueByDays": -15,
      "SiteId": 1,
      "IsNew": 1,
      "Percentage": 0,
      "Status": "Deadline violated",
      "ColorCode": "rgb(239, 65, 54)",
      "ProjectOwner": "Mark Augustin  ",
      "ResourcePercent": 0,
      "Modules": null,
      "User": "Jobi Thomas  ",
      "IsOutputMandatory": 1,
      "ProjectOwnerCheck": 0,
      "TaskOwner": "107",
      "TaskOwnerCheck": 1
    },
    {
      "ProjectID": "272",
      "ActionId": "2720009",
      "Actions": "- Mercury Battery Pack",
      "Description": "Plan Safety Assessments during the Project",
      "ActionType": "Pending Deliverables",
      "site": "Corporate",
      "StartDate": "2023-04-12T09:00:00",
      "DueDate": "2023-04-14T17:30:00",
      "DueByDays": -12,
      "SiteId": 1,
      "IsNew": 1,
      "Percentage": 60,
      "Status": "Deadline violated",
      "ColorCode": "rgb(239, 65, 54)",
      "ProjectOwner": "CP Malini   , Mark Augustin  ",
      "ResourcePercent": 60,
      "Modules": null,
      "User": "Jobi Thomas  ",
      "IsOutputMandatory": 1,
      "ProjectOwnerCheck": 0,
      "TaskOwner": "107",
      "TaskOwnerCheck": 1
    },
    {
      "ProjectID": "313",
      "ActionId": "3130034",
      "Actions": "00_Verification Project",
      "Description": "Future task",
      "ActionType": "Pending Deliverables",
      "site": "Corporate",
      "StartDate": "2023-04-10T09:00:00",
      "DueDate": "2023-04-13T17:30:00",
      "DueByDays": -13,
      "SiteId": 1,
      "IsNew": 1,
      "Percentage": 98,
      "Status": "Deadline violated",
      "ColorCode": "rgb(239, 65, 54)",
      "ProjectOwner": "Mark Augustin  ",
      "ResourcePercent": 98,
      "Modules": null,
      "User": "Jobi Thomas  ",
      "IsOutputMandatory": 1,
      "ProjectOwnerCheck": 0,
      "TaskOwner": "107",
      "TaskOwnerCheck": 1
    },
    {
      "ProjectID": "313",
      "ActionId": "3130035",
      "Actions": "00_Verification Project",
      "Description": "Deliverable 11/4/2023",
      "ActionType": "Pending Deliverables",
      "site": "Corporate",
      "StartDate": "2023-04-11T09:00:00",
      "DueDate": "2023-04-11T17:30:00",
      "DueByDays": -15,
      "SiteId": 1,
      "IsNew": 1,
      "Percentage": 0,
      "Status": "Deadline violated",
      "ColorCode": "rgb(239, 65, 54)",
      "ProjectOwner": "Mark Augustin  ",
      "ResourcePercent": 0,
      "Modules": null,
      "User": "Jobi Thomas  ",
      "IsOutputMandatory": 1,
      "ProjectOwnerCheck": 0,
      "TaskOwner": "107",
      "TaskOwnerCheck": 1
    },
    {
      "ProjectID": "392",
      "ActionId": "3920008",
      "Actions": "00_Folder Testing",
      "Description": "Safety Anomalies Report 5/4",
      "ActionType": "Pending Deliverables",
      "site": "Corporate",
      "StartDate": "2023-03-21T09:00:00",
      "DueDate": "2023-04-04T17:30:00",
      "DueByDays": -22,
      "SiteId": 1,
      "IsNew": 1,
      "Percentage": 90,
      "Status": "Deadline violated",
      "ColorCode": "rgb(239, 65, 54)",
      "ProjectOwner": "Mark Augustin  ",
      "ResourcePercent": 90,
      "Modules": null,
      "User": "Jobi Thomas  ",
      "IsOutputMandatory": 1,
      "ProjectOwnerCheck": 0,
      "TaskOwner": "107",
      "TaskOwnerCheck": 1
    },
    {
      "ProjectID": "392",
      "ActionId": "3920010",
      "Actions": "00_Folder Testing",
      "Description": "Functional Safety Assessment Plan Review and Release",
      "ActionType": "Pending Deliverables",
      "site": "Corporate",
      "StartDate": "2023-04-10T09:00:00",
      "DueDate": "2023-04-11T17:30:00",
      "DueByDays": -15,
      "SiteId": 1,
      "IsNew": 1,
      "Percentage": 0,
      "Status": "Deadline violated",
      "ColorCode": "rgb(239, 65, 54)",
      "ProjectOwner": "Mark Augustin  ",
      "ResourcePercent": 0,
      "Modules": null,
      "User": "Jobi Thomas  ",
      "IsOutputMandatory": 0,
      "ProjectOwnerCheck": 0,
      "TaskOwner": "107",
      "TaskOwnerCheck": 1
    }
  ]