require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false
# Add Flipper dependencies
use_flipper!({ 'Flipper' => '0.125.0' }) # Use the appropriate Flipper version
target 'IntegratedApp' do
  config = use_native_modules!

 def node_require(script)
   # Resolve script with node to allow for hoisting
   require Pod::Executable.execute_command('node', ['-p',
     "require.resolve(
       '#{script}',
       {paths: [process.argv[1]]},
     )", __dir__]).strip
 end

# Use it to require both react-native's and this package's scripts:
 node_require('react-native/scripts/react_native_pods.rb')
 node_require('react-native-permissions/scripts/setup.rb')
  # Add the following for react-native-fetch-blob
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'


  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  setup_permissions([
    # Uncomment only the permissions your app needs
    'Camera',
    'Microphone',
    'LocationWhenInUse',
    'PhotoLibraryAddOnly',
    # Add more permissions as needed...
  ])
  target 'IntegratedAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    flipper_post_install(installer)
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
            # config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
              # # Vision Camera start
              config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
              config.build_settings['HEADER_SEARCH_PATHS'] << '"${PODS_ROOT}/../../node_modules/react-native/ReactCommon" '
              # if target.name === "RNReanimated"
              # config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
              # #Vision Camera end
           end
      end
    end
  end
end
