# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native-permissions/scripts/setup.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
install! 'cocoapods', :deterministic_uuids => false
target 'IntegratedApp' do
  config = use_native_modules!

  # add custom pods before use_react_native!
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'
  pod 'iOSPhotoEditor', :git => 'https://github.com/prscX/photo-editor', :branch => 'master'
  use_frameworks! :linkage => :static
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  setup_permissions([
    # Uncomment only the permissions your app needs
    'Camera',
    'Microphone',
    'LocationWhenInUse',
    'PhotoLibraryAddOnly',
    # Add more permissions as needed...
  ])

  target 'IntegratedAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
          if target.name.include?('iOSPhotoEditor')
            config.build_settings['SWIFT_VERSION'] = '5'
          end
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= '$(inherited) '
          unless config.build_settings['OTHER_CPLUSPLUSFLAGS'].include?('FOLLY_CFG_NO_COROUTINES')
            config.build_settings['OTHER_CPLUSPLUSFLAGS'] << ' -DFOLLY_CFG_NO_COROUTINES'
          end
          # additional header search paths
          config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
          config.build_settings['HEADER_SEARCH_PATHS'] << '"${PODS_ROOT}/../../node_modules/react-native/ReactCommon" '
        end
      end
    end

    installer.aggregate_targets.each do |target|
      target.xcconfigs.each do |_config_name, xcconfig|
        xcconfig.attributes['OTHER_CPLUSPLUSFLAGS'] ||= '$(inherited)'
        unless xcconfig.attributes['OTHER_CPLUSPLUSFLAGS'].include?('FOLLY_CFG_NO_COROUTINES')
          xcconfig.attributes['OTHER_CPLUSPLUSFLAGS'] << ' -DFOLLY_CFG_NO_COROUTINES'
        end
        xcconfig.save_as(target.xcconfig_path(_config_name))
      end
    end
  end
end
