# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native-permissions/scripts/setup.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
install! 'cocoapods', :deterministic_uuids => false
flipper_version = '0.233.0'
target 'IntegratedApp' do
  config = use_native_modules!

  # add custom pods before use_react_native!
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'FlipperKit', flipper_version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', flipper_version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', flipper_version, :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', flipper_version, :configuration => 'Debug'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  setup_permissions([
    # Uncomment only the permissions your app needs
    'Camera',
    'Microphone',
    'LocationWhenInUse',
    'PhotoLibraryAddOnly',
    # Add more permissions as needed...
  ])

  target 'IntegratedAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
          # additional header search paths
          config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
          config.build_settings['HEADER_SEARCH_PATHS'] << '"${PODS_ROOT}/../../node_modules/react-native/ReactCommon" '
        end
      end
    end
  end
end
