import { StyleSheet, Dimensions, Platform } from 'react-native';
import { width, height } from 'react-native-dimension';
import Fonts from '../Themes/Fonts';

let Window = Dimensions.get('window');

export default StyleSheet.create({
    wrapper: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'flex-start',
    },
    header: {
        width: '100%',
        zIndex: 3000,
        flexDirection: 'row',
        //backgroundColor: 'white',
        padding: 5,
        alignItems: 'center',
        justifyContent: 'center',
        height: 60,
        elevation: 4,
        shadowOffset: { width: 2, height: 10 },
        shadowColor: 'lightgrey',
        shadowOpacity: 0.5,
        shadowRadius: 4,
        // flex:1
    },
    backlogo: {
        flexDirection: 'row',
        backgroundColor: 'transparent',
        width: width(15),
        height: 65,
        justifyContent: 'center',
        alignItems: 'center',
    },
    heading: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        width: '70%',
        height: 65,
    },
    headingText: {
        fontSize: Fonts.size.h6,
        // fontFamily : Fonts.type.base,
        color: 'black',
        textAlign: 'center',
        fontFamily: 'OpenSans-Bold',
    },
    headerDiv: {
        width: '15%',
        height: 65,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    footer: {
        bottom: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        backgroundColor: 'transparent',
        height: 65,
        zIndex: 3000,
    },
    footerDiv: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: width(100),
        height: 65,
        position: 'absolute',
    },
    floatingButton: {
        position: 'absolute',
        right: 20,
        bottom: 20,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#123C95',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        zIndex: 3100,
    },
    floatingLabel: {
        marginTop: 4,
        color: 'white',
        fontSize: Fonts.size.small,
        fontFamily: 'OpenSans-Regular',
    },
    auditPageBody: {
        flex: 1,
        zIndex: 10,
        marginLeft: 0,
        marginRight: 0,
        padding: 5,
        backgroundColor: 'white',
        justifyContent: 'center',
        paddingBottom: 0,
        marginBottom: 0,
        alignSelf: 'stretch',
    },
    scrollViewBody: {
        flex: 1,
        backgroundColor: 'transparent',
    },
    simpleTabContainer: {
        flex: 1,
        backgroundColor: 'white',
    },
    simpleTabBar: {
        height: 48,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'white',
        borderBottomWidth: 1,
        borderBottomColor: '#E2E7F0',
    },
    simpleTabText: {
        fontSize: Fonts.size.regular,
        fontFamily: 'OpenSans-SemiBold',
        color: '#123C95',
    },
    headerContainer: {
        backgroundColor: 'transparent',
    },
    tabUnderline: {
        backgroundColor: '#2CB5FD',
        borderBottomColor: '#2CB5FD',
        height: Platform.select({
            android: 0,
            ios: 5,
        }),
    },
    tabText: {
        fontSize: Fonts.size.regular,
        fontFamily: 'OpenSans-Regular',
    },
    networkInfoContainer: {
        marginTop: 60,
        justifyContent: 'center',
        alignItems: 'center',
    },
    noInternetText: {
        fontSize: Fonts.size.h3,
        fontFamily: 'OpenSans-Regular',
    },
    historyContentTopMargin: {
        flex: 1,
    },
    historyLoaderContainer: {
        width: Window.width,
        height: null,
        justifyContent: 'center',
        alignItems: 'center',
    },
    attachmentLinkText: {
        color: 'blue',
    },
    attachmentLinkUnderline: {
        textDecorationLine: 'underline',
    },
    attachmentLinkNoUnderline: {
        textDecorationLine: 'none',
    },
    noRecordsText: {
        fontSize: Fonts.size.h5,
        color: 'grey',
        fontFamily: 'OpenSans-Regular',
    },
    floatingButtonIOSOffset: {
        bottom: 52,
        right: 22,
    },
    floatingButtonAndroidOffset: {
        bottom: 30,
        right: 22,
    },
    toastContainer: {
        backgroundColor: 'black',
        margin: 20,
    },
    toastText: {
        color: 'white',
    },
    card1: {
        width: '100%',
        height: '100%',
        backgroundColor: 'white',
        flexDirection: 'column',
        borderWidth: 0.5,
        borderColor: 'lightgrey',
        elevation: 8,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    card: {
        // width:Window.width,
        // height:290,
        // marginTop:10,
        // justifyContent:'center',
        // alignItems:'center',
        flex: 1,
        margin: 25,
        borderRadius: 8,
    },
    cardT: {
        backgroundColor: 'white',
        width: width(100),
        flexDirection: 'column',
        borderBottomWidth: 0.5,
        borderBottomColor: 'lightgrey',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        paddingTop: 5,
        paddingLeft: 10,
    },
    boxCard1: {
        width: '95%',
        height: '25%',
        backgroundColor: 'white',
        borderBottomWidth: 0.5,
        borderBottomColor: 'lightgrey',
        flexDirection: 'column',
        padding: 10,
    },
    boxCard2: {
        left: 0,
        //marginTop: 11
    },
    detailTitle: {
        fontSize: Fonts.size.medium,
        color: '#A6A6A6',
        fontFamily: 'OpenSans-Regular',
    },
    detailContent: {
        fontSize: Fonts.size.regular,
        color: '#1d1d1d',
        fontFamily: 'OpenSans-Regular',
    },
    div1: {
        width: Window.width,
        //height:height(10),
        backgroundColor: 'transparent',
        marginTop: 10,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
    },
    input07: {
        backgroundColor: 'transparent',
        width: '95%',
        height: '80%',
    },
    calenderModalView: {
        width: Window.width,
        height: null,
        justifyContent: 'center',
        alignItems: 'center',
    },
    calenderView: {
        width: width(90),
        height: '80%',
        backgroundColor: 'white',
        borderRadius: 10,
        flexDirection: 'column',
    },
    calenderHeader: {
        width: '100%',
        height: '10%',
        backgroundColor: 'white',
        top: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderBottomWidth: 0.5,
        borderBottomColor: 'lightgrey',
    },
    calenderBody: {
        width: '100%',
        height: '80%',
        top: 30,
        flex: 1,
        backgroundColor: 'white',
    },
    calenderFooter: {
        width: '100%',
        height: '10%',
        backgroundColor: 'white',
        bottom: 10,
        justifyContent: 'center',
        alignItems: 'center',
        borderTopWidth: 0.5,
        borderTopColor: 'lightgrey',
        paddingTop: 10,
        marginTop: 10,
    },
    auditBox: {
        width: '100%',
        height: 310,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 0.5,
        borderRadius: 5,
        marginBottom: 5,
        elevation: 5,
        borderColor: 'lightgrey',
    },
    Carddiv: {
        width: '95%',
        height: 300,
        backgroundColor: 'white',
        flexDirection: 'column',
    },
    cardS: {
        width: '100%',
        height: '20%',
        backgroundColor: 'white',
        borderBottomWidth: 0.5,
        borderBottomColor: 'lightgrey',
        flexDirection: 'column',
        padding: 5,
    },
    cardLast: {
        width: '100%',
        height: '20%',
        backgroundColor: 'white',
        // borderBottomWidth:0.5,
        // borderBottomColor:'lightgrey',
        flexDirection: 'column',
        padding: 5,
    },
});
