import {StyleSheet, Dimensions} from 'react-native';
import {width, height} from 'react-native-dimension';
import Fonts from '../Themes/Fonts';

let Window = Dimensions.get('window');

export default StyleSheet.create({
  wrapper: {
    flex: 1,
    // flexDirection: 'column',
    // justifyContent: 'flex-start',
  },
  header: {
    width: '100%',
   // zIndex: 3000,
    flexDirection: 'row',
    //backgroundColor: 'white',
    padding: 5,
    alignItems: 'flex-start',
    justifyContent:'space-evenly',
    height: 65,
    elevation: 4,
    shadowOffset: {width: 2, height: 10},
    shadowColor: 'lightgrey',
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  backlogo: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
   // width:width(15),
    height: 65,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backlogoConformance: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    width: width(15),
    height: 65,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heading: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '70%',
    height: 65,
  },
  headingConformance: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: width(60),
    height: 65,
  },
  headingText: {
    fontSize: Fonts.size.mediump,
    color: 'black',
    textAlign: 'center',
    fontFamily: 'OpenSans-Bold',
  },
  headerDiv: {
    // width: width(15),
    height: 65,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerDivConformance: {
    width:'25%',
    height: 65,
    flexDirection: 'row',
    justifyContent:'space-evenly',
    alignItems: 'center',
    marginRight:20
  },
  footer: {
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width:'100%',
    backgroundColor: 'transparent',
    height: 65,
    zIndex: 3000,
  },
  footerDiv: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: width(100),
    height: 65,
    position: 'absolute',
    // flex:1,
    // bottom:20
    // marginBottom:0
  },
  floatingSaveButton: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#00b3d6',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 4,
    zIndex: 3200,
  },
  floatingSaveLabel: {
    marginTop: 4,
    color: 'white',
    fontSize: Fonts.size.small,
    fontFamily: 'OpenSans-Regular',
  },
  auditPageBody: {
    flex: 1,
    zIndex: 10,
    marginLeft: 0,
    marginRight: 0,
    paddingHorizontal: 16,
    paddingTop: 8,
    backgroundColor: '#fff',
    paddingBottom: 0,
    marginBottom: 0,
    marginTop: 10,
  },
  scrollViewBody: {
    height: '70%',
    backgroundColor: 'transparent',
  },
  card1: {
    backgroundColor: 'white',
    width: width(100),
    flexDirection: 'column',
    borderBottomWidth: 0.5,
    borderBottomColor: 'lightgrey',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    padding: 5,
    paddingLeft: 10,
  },
  card: {
    backgroundColor: 'white',
    width: width(100),
    flexDirection: 'column',
    borderBottomWidth: 0.5,
    borderBottomColor: 'lightgrey',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    padding: 5,
    paddingLeft: 10,
  },
  cardT: {
    backgroundColor: 'white',
    width: width(100),
    flexDirection: 'column',
    borderBottomWidth: 0.5,
    borderBottomColor: 'lightgrey',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    paddingTop: 5,
    paddingLeft: 10,
    borderBottomColor: 'lightgrey',
  },
  boxCard1: {
    left: 0,
    //top: 10,
  },
  boxCard: {
    left: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin:10
    //top: 10,
  },
  boxCard2: {
    left: 0,
    //marginTop: 11
  },
  detailTitle: {
    // marginLeft: 35,
    fontSize: Fonts.size.medium,
    color: '#000',
    fontFamily: 'OpenSans-Regular',
  },
  detailContent: {
    fontSize: Fonts.size.regular,
    color: '#1d1d1d',
    fontFamily: 'OpenSans-Regular',
  },
  div1: {
    width: Window.width,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  input07: {
    backgroundColor: 'transparent',
    width: '95%',
    height: '80%',
  },
  calenderModalView: {
    width: Window.width,
    height: null,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calenderView: {
    width: width(90),
    height: '80%',
    backgroundColor: 'white',
    borderRadius: 10,
    flexDirection: 'column',
  },
  calenderHeader: {
    width: '100%',
    height: '10%',
    backgroundColor: 'white',
    top: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    borderBottomColor: 'lightgrey',
  },
  calenderBody: {
    top: 100,
    backgroundColor: 'white',
    width: '100%',
    height: '80%',
    top: 30,
    flex: 1,
    backgroundColor: 'white',
  },
  calenderFooter: {
    width: '100%',
    height: '10%',
    backgroundColor: 'white',
    bottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 0.5,
    borderTopColor: 'lightgrey',
    paddingTop: 10,
    marginTop: 10,
  },
  auditBox: {
    width: '100%',
    height: 310,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0.5,
    borderRadius: 5,
    marginBottom: 5,
    elevation: 5,
    borderColor: 'lightgrey',
  },
  Carddiv: {
    width: '95%',
    height: 300,
    backgroundColor: 'white',
    flexDirection: 'column',
  },
  cardS: {
    width: '100%',
    height: '20%',
    backgroundColor: 'white',
    borderBottomWidth: 0.5,
    borderBottomColor: 'lightgrey',
    flexDirection: 'column',
    padding: 5,
  },
  cardLast: {
    width: '100%',
    height: '20%',
    backgroundColor: 'white',
    // borderBottomWidth:0.5,
    // borderBottomColor:'lightgrey',
    flexDirection: 'column',
    padding: 5,
  },
  uploadButton: {
    backgroundColor: 'transparent',
    width: '90%',
    height: '80%',
  },
  check: {
    position: 'absolute',
    height: '80%',
    width: 32,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    right: 12,
  },
  check1: {
    position: 'absolute',
    width: '60%',
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'transparent',
    right: 12,
    flexDirection: 'row',
  },
  div01: {
    width:'100%',
    backgroundColor: 'transparent',
    marginTop: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderBottomWidth: 0.4,
    borderBottomColor: 'lightgrey',
    paddingBottom: 12,
  },
  manFields: {
    width: '100%',
    backgroundColor: 'transparent',
    marginTop: 12,
    paddingHorizontal: 16,
    alignItems: 'stretch',
    justifyContent: 'center',
    flexDirection: 'column',
    borderBottomWidth: 0.4,
    borderBottomColor: 'lightgrey',
    paddingBottom: 12,
  },

  inputMan: {
    backgroundColor: 'transparent',
    width: '100%',
  },
  ModalBox:{
    width:width(90),
    height:height(80),
    backgroundColor:'white',
    borderRadius:10,
    flexDirection:'column'
  },
  modalheader:{
    width:width(90),
    height:height(9),
    backgroundColor:'transparent',
    top:10,
    justifyContent:'center',
    alignItems:'center',
    borderBottomWidth: 1,
    borderBottomColor: 'white',
    
  },
  sectionContent: {
    flexDirection:'row',
    justifyContent: 'flex-start',
    alignItems: 'center'    
  },
  modalbody:{
    width:width(90),
    // height:height(65),
    backgroundColor:'white',
    padding: 20,
    borderTopWidth:0.5,
    borderTopColor:'lightgrey',
    marginBottom:15

  },
  modalfooter:{
    width:width(90),
    // height:height(9),
    backgroundColor:'white',
    paddingTop: 20,
    bottom:10,
    justifyContent:'center',
    alignItems:'center',
    borderTopWidth:0.5,
    borderTopColor:'lightgrey'
  },
  attachModal: {
    //flex: 1,
    justifyContent: 'center',
    alignItems: 'center', 
    width: '90%',
    //height: '40%',
    backgroundColor: 'white',
    borderRadius: 10,    
    margin: 10,
    padding: 10,
    elevation: 8,
    borderColor: 'lightgrey',
    borderWidth: 0.5
  },
  boxContent: {
    width: '100%',
    color:'black', 
    fontSize: Fonts.size.mediump,
    textAlign: 'center',
    fontFamily:'OpenSans-Regular'
  },
  boxContentCam: {
    //width: '100%',
    color:'#485B9E', 
    fontSize: Fonts.size.mediump,
    fontFamily:'OpenSans-Regular'
    // textAlign: 'center',
    // paddingLeft: 20,
  },
  sectionTop:{
    backgroundColor:'white',
    flexDirection:'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    borderBottomWidth: 0.5,
    borderBottomColor: '#C4C4C4',
    padding: 10    
  },
  modalheading:{
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor:'transparent',
    borderBottomColor: 'lightgrey',
    borderBottomWidth: 0.8,
    justifyContent:'center',
    alignItems:'center',
    padding: 20
  },
  sectionTopCancel:{
    backgroundColor:'white',
    flexDirection:'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    padding: 10    
  },
  boxContentClose: {
    width: '100%',
    color:'#000', 
    textAlign: 'center',
    fontSize: Fonts.size.mediump,
    fontFamily:'OpenSans-Regular'
  },
  fieldCard: {
    width: '100%',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F7F9FC',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 3},
    elevation: 2,
  },
  fieldCardDark: {
    backgroundColor: '#1f2430',
    borderColor: '#2e3443',
    shadowOpacity: 0,
    elevation: 0,
  },
  fieldCardFocused: {
    borderColor: '#1FBFD0',
    shadowOpacity: 0.12,
    elevation: 4,
  },
  fieldLabel: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: Fonts.size.regular,
    color: '#4B5563',
    marginBottom: 6,
  },
  dropdown: {
    width: '100%',
    paddingHorizontal: 0,
    paddingVertical: 4,
    borderWidth: 0,
  },
  dropdownPlaceholder: {
    fontSize: Fonts.size.regular,
    fontFamily: 'OpenSans-Regular',
  },
  dropdownText: {
    fontSize: Fonts.size.regular,
    fontFamily: 'OpenSans-SemiBold',
  },
  commentCard: {
    width: '100%',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F7F9FC',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 3},
    elevation: 2,
  },
  commentInput: {
    width: '100%',
    minHeight: 70,
    fontFamily: 'OpenSans-Regular',
    fontSize: Fonts.size.regular,
    paddingTop: 6,
  },
  commentLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
});
