import { StyleSheet, Dimensions, Platform } from 'react-native';
import Fonts from '../Themes/Fonts';
import { width, height } from 'react-native-dimension';
import { COLORS, SPACING } from 'constants/theme-constants';

let Window = Dimensions.get('window');
const loaderMarginTop = Window.height / 2 - 200;
const attachmentHeight = loaderMarginTop + 100;

export default StyleSheet.create({
    // // Header styles
    // header: {
    //     width: '100%',
    //     flexDirection: 'row',
    //     justifyContent: 'space-between',
    //     //alignContent:'center',
    //     height: 65,
    //     elevation: 4,
    //     shadowOffset: { width: 2, height: 10 },
    //     shadowColor: 'lightgrey',
    //     shadowOpacity: 0.5,
    //     shadowRadius: 4,
    // },
    // header1: {
    //     flexDirection: 'row',
    //     justifyContent: 'space-between',
    //     alignContent: 'center',
    // },
    // heading: {
    //     flexDirection: 'column',
    //     justifyContent: 'center',
    //     alignItems: 'center',
    //     width: '60%',
    //     height: 65,
    // },
    // headingText: {
    //     fontSize: Fonts.size.mediump,
    //     color: '#000000',
    //     textAlign: 'center',
    //     fontFamily: 'OpenSans-Bold',
    // },
    // backlogo: {
    //     flexDirection: 'row',
    //     backgroundColor: 'transparent',
    //     width: '35%',
    //     height: 65,
    //     justifyContent: 'center',
    //     alignItems: 'center',
    // },
    // headerDiv: {
    //     width: '15%',
    //     height: 65,
    //     flexDirection: 'row',
    //     justifyContent: 'center',
    //     alignItems: 'center',
    // },
    // rightHeader: {
    //     flexDirection: 'row',
    //     justifyContent: 'flex-end',
    //     alignItems: 'center',
    //     right: 10,
    //     height: 80,
    // },
    // backgroundImage: {
    //     resizeMode: 'stretch',
    //     width: width(30),
    //     height: 80,
    //     zIndex: 0,
    // },

    // Footer styles
    footer: {
        bottom: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        backgroundColor: '#FFFFFF',
        paddingVertical: 8,
        paddingHorizontal: 10,
    },
    footerDiv: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignContent: 'center',
        width: '100%',
    },
    footerResponsiveWrap: {
        alignSelf: 'center',
        width: '100%',
    },
    footerLoader: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    footerTextContent: {
        color: '#ffffff',
        fontSize: 14,
        fontFamily: 'OpenSans-SemiBold',
        paddingTop: 6,
        lineHeight: 18,
        minHeight: 42,
        textAlign: 'center',
        textAlignVertical: 'center',
        width: '100%',
    },
    footerShadowButton: {
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 84,
        paddingVertical: 12,
        paddingHorizontal: 10,
        borderRadius: 10,
        backgroundColor: COLORS.primaryDarkThemeColor,
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowOffset: {width: 0, height: 2},
        shadowRadius: 2,
        elevation: 1,
        width: '100%',
    },
    footerDivContent: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    footerButtonsRow: {
        flexDirection: 'row',
        alignItems: 'stretch',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: 6,
    },
    footerButtonWrapper: {
        flex: 1,
        minWidth: 0,
        marginHorizontal: 4,
        justifyContent: 'center',
    },

    // Body styles
    auditPageBody: {
        flex: 1,
        zIndex: 10,
        marginLeft: 0,
        marginRight: 0,
        padding: 5,
        backgroundColor: 'white',
        justifyContent: 'center',
        paddingBottom: 0,
        marginBottom: 0,
        alignSelf: 'stretch',
    },
    auditPageBodyResponsive: {
        alignSelf: 'center',
        width: '100%',
    },
    wrapper: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'flex-start',
        backgroundColor: '#FFFFFF',
    },

    // Card view styles
    scrollViewBody: {
        height: '100%',
        backgroundColor: 'transparent',
    },
    cardBox: {
        backgroundColor: 'white',
        margin: 5,
        elevation: 3,
        flexDirection: 'column',
        borderRadius: 5,
        padding: 5,
        borderWidth: 0.5,
        borderColor: 'lightgrey',
    },
    sectionTop: {
        backgroundColor: 'white',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        borderBottomWidth: 0.5,
        borderBottomColor: 'lightgrey',
        padding: 10,
    },
    sectionBottom: {
        backgroundColor: 'white',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        padding: 10,
    },
    sectionContent: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    boxHeader: {
        width: '100%',
        color: '#A6A6A6',
        fontSize: Fonts.size.small,
        fontFamily: 'OpenSans-Regular',
    },
    boxContent: {
        width: '100%',
        color: '#485B9E',
        fontSize: Fonts.size.regular,
        fontFamily: 'OpenSans-Regular',
    },

    body: {
        width: Window.width,
        height: '90%',
        backgroundColor: 'transparent',
        position: 'absolute',
        top: height(10),
        flexDirection: 'column',
        // justifyContent: 'center',
        // alignItems: 'center'
    },
    button1: {
        width: Window.width,
        height: height(32),
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        bottom: 20,
    },
    btnbox: {
        width: width(80),
        height: height(38),
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },

    button2: {
        width: Window.width,
        height: height(14),
        backgroundColor: 'transparent',
        flexDirection: 'row',
        bottom: 20,
    },
    button12: {
        width: Window.width,
        height: height(14),
        backgroundColor: 'transparent',
        // flexDirection: 'row',
        //  bottom:20
    },
    button02: {
        width: Window.width,
        height: height(15),
        backgroundColor: 'transparent',
        flexDirection: 'row',
        top: 0,
    },
    box1: {
        top: 0.5,
        width: Window.width / 2,
        height: height(15),
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'transparent',
    },
    box2: {
        width: Window.width / 2,
        height: height(20),
        justifyContent: 'center',
        alignItems: 'center',
    },
    box1img: {
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        width: '80%',
        height: '80%',
        borderWidth: 1,
        borderRadius: 8,
        backgroundColor: 'white',
    },
    button3: {
        width: Window.width,
        height: height(40),
        backgroundColor: 'black',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    SectionHeaderStyle: {
        backgroundColor: '#b9ff87',
        fontSize: Fonts.size.regular,
        padding: 5,
        color: '#000',
        width: width(90),
        justifyContent: 'center',
        alignItems: 'center',
        borderTopRightRadius: 5,
        borderTopLeftRadius: 5,
    },
    SectionListItemStyle: {
        fontSize: Fonts.size.regular,
        marginBottom: 5,
        color: 'black',
        backgroundColor: 'white',
        borderBottomColor: 'lightgrey',
        borderBottomWidth: 0.8,
        height: height(8),
        width: width(90),
        justifyContent: 'center',
        alignItems: 'center',
        borderBottomRightRadius: 5,
        borderBottomLeftRadius: 5,

        // fontWeight: 'bold'
    },
    modalBody: {
        width: width(100),
        height: height(100),
        backgroundColor: 'white',
        borderRadius: 8,
    },
    modalheading: {
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: 'transparent',
        borderBottomColor: 'lightgrey',
        borderBottomWidth: 0.8,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalfooter: {
        width: '100%',
        height: '10%',
        backgroundColor: 'grey',
        position: 'absolute',
        borderBottomColor: 'lightgrey',
        borderBottomWidth: 0.8,
        justifyContent: 'center',
        alignItems: 'center',
        bottom: height(2),
    },
    scrollView: {
        marginTop: height(10),
        height: '80%',
        width: '100%',
        backgroundColor: 'transparent',
    },
    ///
    cardDiv: {
        width: Window.width,
        height: height(17),
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 5,
        padding: 20,
    },
    cardDivBox: {
        width: width(95),
        height: height(16),
        backgroundColor: 'white',
        elevation: 5,
        flexDirection: 'column',
        borderRadius: 5,
    },
    Box01: {
        width: '100%',
        height: height(8),
        backgroundColor: 'transparent',
    },
    Box: {
        width: '100%',
        height: height(8),
        backgroundColor: 'transparent',
        borderTopWidth: 0.5,
    },
    Section1: {
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    Section2: {
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    Box1: {
        position: 'absolute',
        height: height(8),
        width: '100%',
        padding: 5,
    },
    Box2: {
        position: 'absolute',
        height: height(8),
        width: '30%',
        backgroundColor: 'transparent',
        right: 0,
    },
 
    ncModal: {
        justifyContent: 'center',
        alignItems: 'center',
        height: 500,
        backgroundColor: 'white',
        borderRadius: 10,
        flexDirection: 'column',
        padding: 10,
    },
    ModalBox: {
        width: '90%',
        height: height(50),
        backgroundColor: 'white',
        borderRadius: 10,
        flexDirection: 'column',
        top: height(40),
    },
    scrollview: {
        width: '100%',
        // height:350,
        backgroundColor: 'transparent',
        // justifyContent:'center',
        alignContent: 'center',
        flexDirection: 'column',
    },
    modalheader: {
        width: '100%',
        height: 60,
        backgroundColor: 'white',
        // justifyContent:'center',
        alignContent: 'center',
        borderBottomColor: 'lightgrey',
        borderBottomWidth: 0.5,
    },
    firstCard: {
        width: '100%',
        // height:60,
        backgroundColor: 'transparent',
        flexDirection: 'column',
    },
    commoncard: {
        width: '100%',
        // height:60,
        backgroundColor: 'transparent',
        flexDirection: 'column',
        borderTopColor: 'lightgrey',
        borderTopWidth: 0.4,
    },
    lastcard: {
        width: '100%',
        // height:60,
        backgroundColor: 'transparent',
        flexDirection: 'column',
        borderTopColor: 'lightgrey',
        borderTopWidth: 0.4,
        // paddingBottom:height(60)
    },
    modalbody: {
        width: '90%',
        height: height(42),
        backgroundColor: 'white',
        padding: 20,
    },
    modalfooter: {
        width: '90%',
        // height:height(9),
        backgroundColor: 'transparent',
        paddingTop: 10,
        bottom: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    closeDiv: {
        width: '100%',
        height: 60,
        backgroundColor: 'white',
        // justifyContent:'center',
        alignContent: 'center',
        borderTopColor: 'lightgrey',
        borderTopWidth: 0.5,
    },
    norecordefound: {
        //  width: width(100),
        textAlign: 'center',
        marginTop: '5%',
        fontSize: Fonts.size.h5,
        // paddingTop: 40,
        color: 'grey',
        fontFamily: 'OpenSans-Regular',
    },
    missingModal: {
        width: '100%',
        height: null,
        backgroundColor: 'white',
        borderRadius: 10,
        flexDirection: 'column',
    },
    missingMContainer: {
        width: '100%',
        height: 80,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        borderBottomColor: 'lightgrey',
        borderBottomWidth: 0.7,
    },
    missingBody: {
        width: '100%',
        height: 300,
    },
    missingBodyHeader: {
        width: '100%',
        height: null,
        padding: 20,
        flexDirection: 'column',
    },
    bodyText1: {
        color: 'grey',
        fontSize: 16,
        fontFamily: 'OpenSans-Regular',
    },
    bodyText2: {
        color: 'black',
        fontSize: 18,
        fontFamily: 'OpenSans-Regular',
    },
    scrollBody: {
        width: '100%',
        height: '65%',
    },
    carddivMissing: {
        width: '100%',
        height: null,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    cardContMissing: {
        width: '95%',
        height: 90,
        borderLeftWidth: 6,
        borderLeftColor: 'red',
        borderRadius: 10,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 0.5,
    },
    cardSecMissing: {
        width: '95%',
        height: '50%',
        justifyContent: 'center',
        borderBottomWidth: 0.7,
        borderBottomColor: 'grey',
        flexDirection: 'column',
    },
    cardsec2Missing: {
        width: '95%',
        height: '50%',
        justifyContent: 'center',
    },
    cardFooterMissing: {
        width: '100%',
        height: 80,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        borderTopColor: 'lightgrey',
        borderTopWidth: 0.7,
        flexDirection: 'row',
    },
    cardBtnDiv: {
        width: '50%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRightColor: 'lightgrey',
        borderRightWidth: 0.7,
    },
    cardBtn2Div: {
        width: '50%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },

    // Spacers
    topSpacerIos: {
        padding: SPACING.MEDIUM,
        flexDirection: 'row',
    },
    topSpacerAndroid: {
        padding: SPACING.NORMAL,
        flexDirection: 'row',
    },

    // Layout helpers
    auditPageBodyPadded: {
        paddingTop: 10,
    },
    listMarginTop: {
        marginTop: 55,
    },
    row: {
        flexDirection: 'row',
    },
    deleteIconContainer: {
        flex: 1,
        flexDirection: 'row',
        alignSelf: 'flex-end',
    },
    emptyStateWrapper: {
        marginTop: '20%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyStateRow: {
        flexDirection: 'row',
        justifyContent: 'center',
    },
    emptyStateLottie: {
        width: Window.width * 0.44,
        height: Window.width * 0.44,
    },
    emptyStateImage: {
        height: 50,
        resizeMode: 'contain',
    },
    flexOne: {
        flex: 1,
    },

    // Attachments
    attachmentList: {
        marginTop: 10,
    },
    loadingRow: {
        flexDirection: 'row',
        paddingBottom: 10,
    },
    hourglassIcon: {
        padding: 5,
    },
    loadingText: {
        color: '#A6A6A6',
        fontFamily: 'OpenSans-Regular',
        alignSelf: 'flex-start',
        padding: 5,
    },
    attachmentItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        margin: 2,
        borderColor: '#2a4944',
        borderWidth: 1,
        height: '90%',
    },
    columnFlex: {
        flexDirection: 'column',
    },
    attachmentFilenameWrapper: {
        width: width(65),
        marginTop: 1,
        alignContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
    },
    attachmentImage: {
        width: width(65),
        height: 200,
        resizeMode: 'cover',
        alignSelf: 'center',
    },
    attachmentIcon: {
        paddingTop: 70,
        height: 200,
        flex: 1,
        justifyContent: 'center',
        alignSelf: 'center',
    },
    syncFileIcon: {
        padding: 6,
        justifyContent: 'center',
        alignSelf: 'center',
    },
    uploadStatusHeader: {
        paddingBottom: 10,
        fontWeight: 'bold',
        alignItems: 'center',
        alignSelf: 'center',
    },
    uploadItemRow: {
        flex: 1,
        flexDirection: 'row',
        borderBottomWidth: 1,
        minHeight: 40,
        maxHeight: 60,
        borderBottomColor: 'lightgrey',
    },
    uploadIconWrapper: {
        justifyContent: 'center',
        width: '5%',
    },
    uploadFileNameWrapper: {
        width: '85%',
        justifyContent: 'center',
    },
    uploadFileName: {
        justifyContent: 'center',
        flexShrink: 1,
        paddingLeft: 2,
        color: 'black',
    },
    uploadFileNameMissing: {
        color: 'red',
    },
    uploadStatusWrapper: {
        width: '10%',
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
    },
    retryWrapper: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    retryText: {
        fontSize: 10,
        color: 'red',
    },
    boxHeaderMarginTop: {
        marginTop: 5,
    },

    // Loader / sync
    loaderContainer: {
        alignItems: 'center',
        marginTop: loaderMarginTop,
    },
    loaderText: {
        textAlign: 'center',
        fontFamily: 'OpenSans-Regular',
    },
    attachmentStatusContainer: {
        alignItems: 'center',
        paddingTop: 20,
        height: attachmentHeight,
    },
    proceedWrapper: {
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    proceedButton: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 84,
        paddingVertical: 12,
        paddingHorizontal: 10,
        borderRadius: 10,
        backgroundColor: COLORS.primaryDarkThemeColor,
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 2,
        elevation: 1,
    },
    proceedText: {
        color: '#ffffff',
        fontSize: 14,
        marginTop: 6,
        lineHeight: 18,
        minHeight: 42,
        textAlign: 'center',
        textAlignVertical: 'center',
        fontFamily: 'OpenSans-SemiBold',
        width: '100%',
    },
    activityWrapper: {
        width: '100%',
        minHeight: 84,
        paddingVertical: 12,
        paddingHorizontal: 10,
        borderRadius: 10,
        backgroundColor: COLORS.primaryDarkThemeColor,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 2,
        elevation: 1,
    },

    // Missing attachment modal
    missingTitle: {
        fontSize: 22,
        color: '#2EA4E2',
        fontFamily: 'OpenSans-Regular',
    },
    missingLabel: {
        fontFamily: 'OpenSans-Regular',
    },
    missingNCNumber: {
        fontSize: 15,
        color: '#37057E',
        fontFamily: 'OpenSans-Regular',
    },
    missingNCText: {
        fontSize: 15,
        color: '#070F6E',
        fontFamily: 'OpenSans-Regular',
    },
    goBackText: {
        fontSize: 20,
        color: 'red',
        fontFamily: 'OpenSans-Regular',
    },
    skipText: {
        fontSize: 20,
        color: 'green',
        fontFamily: 'OpenSans-Regular',
    },

    // Detail modal
    modalHeaderContent: {
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
    },
    modalTitle: {
        color: 'black',
        fontSize: 23,
        fontFamily: 'OpenSans-Regular',
    },
    detailTopSpacing: {
        marginTop: 10,
    },
    loadingCard: {
        width: '100%',
        height: 200,
        justifyContent: 'center',
        alignContent: 'center',
    },
    loadingCardInner: {
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
    },
    loadingCardText: {
        fontFamily: 'OpenSans-Regular',
    },
    errorCard: {
        width: '100%',
        top: 90,
        height: 200,
        justifyContent: 'center',
        alignContent: 'center',
    },
    closeButtonWrapper: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    closeButtonText: {
        fontSize: Fonts.size.regular,
        color: '#00a1e2',
        top: 20,
        fontFamily: 'OpenSans-Regular',
    },

    // Confirm password modal
    confirmModal: {
        width: '100%',
        height: 350,
        backgroundColor: 'white',
        borderRadius: 15,
        padding: 10,
    },
    confirmTitle: {
        textAlign: 'center',
        fontSize: 20,
        color: '#2EA4E2',
        fontFamily: 'OpenSans-Bold',
    },
    closeIcon: {
        alignSelf: 'flex-end',
    },
    centeredFlex: {
        flex: 1,
    },
    centeredFlexRow: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    inputLabel: {
        fontSize: 16,
        color: 'grey',
        fontFamily: 'OpenSans-Regular',
    },
    textInputBase: {
        fontSize: 20,
        fontFamily: 'OpenSans-Bold',
        borderBottomColor: 'lightgrey',
        borderBottomWidth: 0.7,
    },
    textInputReadonly: {
        color: 'lightgrey',
    },
    textInputEditable: {
        color: 'black',
    },
    inputError: {
        fontSize: 16,
        color: 'red',
        fontFamily: 'OpenSans-Regular',
    },
    confirmButtonContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    confirmButton: {
        width: null,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#2EA4E2',
        borderRadius: 30,
        padding: 10,
    },
    confirmButtonText: {
        fontFamily: 'OpenSans-Bold',
        fontSize: 20,
        color: 'white',
    },
    confirmDialogTitle: {
        fontFamily: 'OpenSans-SemiBold',
    },
    confirmDialogMessage: {
        fontFamily: 'OpenSans-Regular',
    },

    // Tabs
    tabUnderline: {
        backgroundColor: COLORS.primaryDarkThemeColor,
        borderBottomColor: COLORS.primaryDarkThemeColor,
        height: Platform.select({
            android: 0,
            ios: 5,
        }),
    },
    tabText: {
        fontSize: Fonts.size.h5,
        fontFamily: 'OpenSans-Regular',
    },
});
