import { StyleSheet } from "react-native";
import Fonts from "../../themes/Fonts";
import { width, height } from "react-native-dimension";
export default StyleSheet.create({
  container: {
    flex: 1,
    height: 40,
  },
  wrapper: {
    // flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    //position: "relative",
    //padding: 10,
    height: 65,
    bottom: 0,
    zIndex: 60000,
    borderTopWidth: 1,
    borderTopColor: "lightgrey",
  },
  wrapperFoot: {
    // flex: 1,
    flexDirection: "row",
    //position: 'absolute',
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    height: 65,
    bottom: 0,
    zIndex: 60000,
    // borderTopWidth: 1,
    // borderTopColor: "lightgrey",
    // marginTop:50,
  },

  background: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "transparent",
  },
  header: {
    color: "#fff",
    fontSize: Fonts.size.h5,
    backgroundColor: "transparent",
  },
  name: {
    color: "#fff",
    fontSize: Fonts.size.h4,
    marginLeft: 20,
    fontWeight: "bold",
    backgroundColor: "transparent",
  },
  avatar: {
    width: 100,
    height: 100,
    marginTop: 80,
    marginLeft: 20,
    marginBottom: 20,
    borderRadius: 50,
  },
  footerMenuItem: {
    flexDirection: "column",
    // width: width(32),
    // width:'25%',
    height: 60,
    flex: 1,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    // textAlign: 'center',
    // color: 'white',
    backgroundColor: "transparent",
  },

  footerMenuItem2: {
    flexDirection: "column",
    // width: width(32),
    // width:'25%',
    height: 60,
    flex: 1,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    // textAlign: 'center',
    // color: 'white',
    backgroundColor: "transparent",
    marginBottom: 120,
  },
  separatorSection: {
    flexDirection: "column",
    alignItems: "center",
    width: width(0.2),
    height: 40,
    borderWidth: 0,
    backgroundColor: "lightgrey",
    marginTop: 10,
    marginBottom: 10,
  },
});
