import { StyleSheet, Dimensions } from "react-native";
import { Metrics, ApplicationStyles } from "../../themes";
import Fonts from "../../themes/Fonts";
import { width, height } from "react-native-dimension";

let Window = Dimensions.get("window");

export default StyleSheet.create({
  ...ApplicationStyles.screen,
  fillcontainer: {
    flex: 1,
  },
  dateRange: {
    fontSize: Fonts.size.medium,
    color: "grey",
    margin: 5,
    padding: 5,
    marginBottom: 0,
    textAlign: "center",
  },
  mainContainer: {
    flex: 1,
    width: Window.width,
    // height: Window.height,
    height: "85%",
    paddingBottom:70,
  },
  mainContainer1: {
    flex: 1,
    width: Window.width,
    height: Window.height,
    paddingBottom:40,
  },
  bgImage: {
    width: Window.width,
    height: "170%",
    resizeMode: "cover",
  },
  apqpTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    //color:'black',
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  apqpTextStyle: {
    fontSize: 24,
    color: "white",
  },
  segmentControlTabView: {
    position: "absolute",
    height: "100%",
    width: "80%",
    //borderColor:'black',
    marginTop: 50,
    marginLeft: 20,
    paddingBottom: 15,
  },
  segmentControlTab: {
    borderColor: "#00bec3",
    height: 60,
    // backgroundColor:'#00bec3'
    backgroundColor: "white",
  },
  activeTabStyle: {
    backgroundColor: "white",
  },
  activeTabTextStyle: {
    color: "#00b1cf",
  },
  tabTextStyle: {
    color: "grey",
    fontSize: 16,
  },
  tabsContainerStyle: {
    width: Metrics.screenWidth,
  },
  buttonStyles: {
    borderTopColor: "transparent",
    flexDirection: "column",
  },
  buttonTouchableStyle: {
    width: 100,
    height: 30,
    borderRadius: 50,
    borderWidth: 0.5,
    elevation: 1,
    borderColor: "lightgrey",
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#AFAAAC",
  },
  buttonView: {
    paddingLeft: 10,
    borderColor: "#AFAAAC",
  },
  listText: {
    color: "#AFAAAC",
    fontSize: Fonts.size.medium,
    padding: 2,
    marginLeft: 20,
  },
  flatList: {
    width: Window.width,
    padding: 5,
  },
  flatListView: {
    flex: 1,
    padding: 3,
    marginLeft: 15,
    marginRight: 5,
    //marginBottom: 20,
    // borderColor: "red",
    // borderWidth: 2,
  },
  flatListTouchableView: {
    width: "100%",
    flex: 4,
    paddingBottom: 10,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: 0,
    borderBottomWidth: 0.5,
    borderBottomColor: "lightgrey",
    flexDirection: "row",
  },
  flatListInsideView: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    height: 25,
  },
  actionTypeTextStylecb: {
    color: "#485B9E",
    fontSize: Fonts.size.regular,
  },
  actionTypeTextStyle: {
    color: "#7F7D7D",
    fontSize: Fonts.size.regular,
  },
  actionTypeTextStyleSite: {
    color: "#7F7D7D",
    fontSize: Fonts.size.medium,
  },
  dateTextStyle: {
    color: "#7F7D7D",
    fontSize: Fonts.size.medium,
  },
  actionTypeTextStyleDesc: {
    color: "#7F7D7D",
    fontSize: Fonts.size.regular,
    width: "55%",
  },
  actionTypeLineStyle: {
    //borderBottomColor:'black',
    //borderBottomWidth:0.5
  },
  recordStyle: {
    fontSize: Fonts.size.input,
  },
  circleView: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "30%",
    position: "absolute",

    backgroundColor: "red",
  },
  progressVal: {
    fontSize: Fonts.size.medium,
    color: "#1d1d1d",
  },
  footerDiv: {
    width: "100%",
    height: 60,
    backgroundColor: "transparent",
    position: "absolute",
    bottom: 0,
    borderTopColor: "grey",
    borderTopWidth: 0.5,
  },
  projectText: {
    flexDirection: "column",
    width: width(45),
    justifyContent: "center",
    alignItems: "center",
  },

  actionText: {
    flexDirection: "column",
    width: width(45),
    justifyContent: "center",
    alignItems: "center",
  },
  lineIconStyle: {
    width: width(10),
    justifyContent: "center",
    alignItems: "center",
  },
  footerContainer: {
    width: "100%",
    height: 70,
    backgroundColor: "transparent",
    flexDirection: "row",
  },
  footerButton: {
    width: "50%",
    height: "100%",
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerButton1: {
    width: "50%",
    height: 60,
    padding: 10,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerButton2: {
    flexDirection: "column",
    // width: width(32),
    // width:'25%',
    height: 60,
    flex: 1,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    // textAlign: 'center',
    // color: 'white',
    backgroundColor: "transparent",
  },
  // backLogo: {
  //   width: "10%",
  //   height: 70,
  //   justifyContent: "center",
  //   alignItems: "center",
  // },
  headerDiv: {
    width: width(50),
    height: 65,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 25,
  },
  calendarDivicon: {
    width: "20%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  segmentDiv: {
    width: "100%",
    height: 75,
    backgroundColor: "transparent",
    flexDirection: "row",
  },
  segmentBox2: {
    width: "40%",
    height: 60,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    borderRightColor: "white",
    borderRightWidth: 0.5,
  },
  segmentBox1: {
    width: "30%",
    height: 60,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    borderRightColor: "white",
    borderRightWidth: 0.5,
  },
  segmentBox: {
    width: "30%",
    height: 60,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
  },
  activeTab: {
    color: "white",
    fontSize: 14,
    fontWeight: "bold",
  },
  activeTabCount: {
    color: "white",
    fontSize: 26,
    fontWeight: "bold",
  },
  calendarDiv: {
    width: "100%",
    backgroundColor: "white",
    borderRadius: 10,
    padding: 10,
  },
  header: {
    width: "100%",
    height: 70,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    borderBottomColor: "lightgrey",
    borderBottomWidth: 0.5,
  },
  footer: {
    width: "100%",
    height: 55,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: "lightgrey",
    borderTopWidth: 0.5,
  },
  quickModaldiv: {
    width: "100%",
    height: 250,
    backgroundColor: "white",
    borderRadius: 5,
    padding: 10,
  },
  quickheader: {
    width: "100%",
    height: 60,
    backgroundColor: "white",
    borderBottomWidth: 0.5,
    borderBottomColor: "lightgrey",
    justifyContent: "center",
    alignItems: "center",
  },
  quickBody: {
    width: "100%",
    height: 110,
    backgroundColor: "white",
    marginTop: 10,
  },
  textDiv: {
    width: "100%",
    // justifyContent:'center',
    // alignItems:'center',
    borderBottomColor: "lightgrey",
    borderBottomWidth: 0.5,
    flexDirection: "row",
  },
  quickFooter: {
    width: "100%",
    height: 60,
    backgroundColor: "white",
    borderTopWidth: 0.5,
    borderTopColor: "lightgrey",
    // justifyContent:'center',
    // alignItems:'center'
    flexDirection: "row",
  },
  btnDiv: {
    width: "50%",
    height: 60,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  btnDiv2: {
    width: "50%",
    height: 60,
    backgroundColor: "white",
    borderLeftWidth: 0.5,
    borderLeftColor: "grey",
    justifyContent: "center",
    alignItems: "center",
  },

  dullTextOverall: {
    width: "85%",
    height: 20,
    fontSize: 11,
    color: "grey",
  },

  progressText: {
    fontSize: 13,
    color: "#485B9E",
  },
  searchDiv: {
    width: "100%",
    height: 40,
    backgroundColor: "white",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  dropdowndiv: {
    flex: 1,
    width: "40%",
    height: 40,
    flexDirection: "row",
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  LabelText: {
    paddingLeft: 5,
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  header: {
    width: "100%",
    height: 50,
    alignItems: "center",
    flexDirection: "row",
  },
  heading: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width(70),
    height: 65,
  },
  heading: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width(70),
    height: 65,
  },
  headingText: {
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  footer: {
    width: "100%",
    height: 48,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: "lightgrey",
    borderTopWidth: 0.5,
  },
  bodyCont: {
    width: "100%",
    height: "100%",
  },
  bodyCont1: {
    width: "100%",
    height: "80%",
  },
  bodyCont2: {
    width: "100%",
    height: "100%",
  },
  projectBox: {
    flex: 1,
    flexDirection: "row",
    padding: 10,
    marginLeft: 5,
    marginRight: 5,
    marginBottom: 0,
    // borderColor: 'red',
    // borderWidth: 1,
    // borderRadius: 1,
    // shadowColor: '#000',
    // shadowOffset: {width: 0, height: 2},
    // shadowOpacity: 0.8,
    // shadowRadius: 2,
    // elevation: 1,
    height: undefined,
    borderBottomColor: "#DEDBDB",
    borderBottomWidth: 0.5,
  },
  projectBoxStatus: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    padding: 10,
    position: "absolute",
    right: 0,
    paddingLeft: 5,
  },
  projectBoxContent: {
    flexDirection: "column",
    justifyContent: "flex-start",
    //width: width(75),
    padding: 10,
    backgroundColor:'#fff',
    right: '4%',
    // marginLeft: '2%',
    //   borderColor: "green",
    //   borderWidth: 2,
  },
  apqpTypeIcon: {
    width: 20,
    height: 17,
    left: 5,
    top: 5,
    position: "absolute",
  },
  filterCont: {
    width: "100%",
    height: 50,
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "lightgrey",
    // marginTop: 40,
  },
  filterBox: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    // borderLeftColor:"lightgrey",
    // borderLeftWidth:0.7
  },
  scrollViewBody: {
    height: "100%",
    backgroundColor: "transparent",
  },
  renderFilterView: {
    // width:null,
    // height:null,
    padding: 5,
    margin: 5,
    borderRadius: 5,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "lightgrey",
    // flexDirection: 'row',
    // marginLeft: 6,
    // justifyContent: 'center',
    // alignItems: 'center',
    // borderRadius: 5
  },

  separatorSection: {
    flexDirection: "column",
    alignItems: "center",
    width: width(0.2),
    height: 40,
    borderWidth: 0,
    backgroundColor: "lightgrey",
    marginTop: 10,
    marginBottom: 10,
  },
  backlogo: {
    flexDirection: "row",
    backgroundColor: "transparent",
    width: width(15),
    height: 65,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionHeaderContainer: {
    backgroundColor: '#fff',
    paddingVertical: 5,
    paddingHorizontal: 10,
    flexDirection: "column",
    justifyContent: "flex-start",
    left: '4%',
    width: width(93),
  },

  sectionHeader: {
    backgroundColor: '#e6f7f8',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#1FBFD0',
  },

  sectionHeaderText: {
    fontSize: Fonts.size.h5,
    fontWeight: "bold",
    color: '#1FBFD0',
  },

});
