import { StyleSheet, Dimensions } from "react-native";
import { Metrics, ApplicationStyles } from "../../themes";
import Fonts from "../../themes/Fonts";
import { width, height } from "react-native-dimension";
import { SPACING } from "constants/theme-constants";

let Window = Dimensions.get("window");

export default StyleSheet.create({
  ...ApplicationStyles.screen,
  fillcontainer: {
    flex: 1,
  },
  dateRange: {
    fontSize: Fonts.size.medium,
    color: "grey",
    margin: 5,
    padding: 5,
    marginBottom: 0,
    textAlign: "center",
  },
  mainContainer: {
    flex: 1,
    width: Window.width,
    height: "85%",
    paddingBottom: height(8),
  },
  mainContainer1: {
    flex: 1,
    width: Window.width,
    height: Window.height,
    paddingBottom: height(5),
  },
  bgImage: {
    width: Window.width,
    height: "170%",
    resizeMode: "cover",
  },
  apqpTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  apqpTextStyle: {
    fontSize: 24,
    color: "white",
  },
  segmentControlTabView: {
    position: "absolute",
    height: "100%",
    width: "80%",
    marginTop: height(6),
    marginLeft: width(5),
    paddingBottom: 15,
  },
  segmentControlTab: {
    borderColor: "#00bec3",
    minHeight: height(7),
    backgroundColor: "white",
  },
  activeTabStyle: {
    backgroundColor: "white",
  },
  activeTabTextStyle: {
    color: "#00b1cf",
  },
  tabTextStyle: {
    color: "grey",
    fontSize: 16,
  },
  tabsContainerStyle: {
    width: Metrics.screenWidth,
  },
  buttonStyles: {
    borderTopColor: "transparent",
    flexDirection: "column",
  },
  buttonTouchableStyle: {
    width: width(24),
    minHeight: height(4),
    borderRadius: 50,
    borderWidth: 0.5,
    elevation: 1,
    borderColor: "lightgrey",
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#AFAAAC",
  },
  buttonView: {
    paddingLeft: 10,
    borderColor: "#AFAAAC",
  },
  listText: {
    color: "#AFAAAC",
    fontSize: Fonts.size.medium,
    padding: 2,
    marginLeft: width(5),
  },
  flatList: {
    width: Window.width,
    padding: 5,
  },
  flatListView: {
    flex: 1,
    padding: 3,
    marginLeft: 15,
    marginRight: 5,
    //marginBottom: 20,
    // borderColor: "red",
    // borderWidth: 2,
  },
  flatListTouchableView: {
    width: "100%",
    flex: 4,
    paddingBottom: 10,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: 0,
    borderBottomWidth: 0.5,
    borderBottomColor: "lightgrey",
    flexDirection: "row",
  },
  flatListInsideView: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    minHeight: height(3.2),
  },
  actionTypeTextStylecb: {
    color: "#485B9E",
    fontSize: Fonts.size.regular,
  },
  actionTypeTextStyle: {
    color: "#7F7D7D",
    fontSize: Fonts.size.regular,
  },
  actionTypeTextStyleSite: {
    color: "#7F7D7D",
    fontSize: Fonts.size.medium,
  },
  dateTextStyle: {
    color: "#7F7D7D",
    fontSize: Fonts.size.medium,
  },
  actionTypeTextStyleDesc: {
    color: "#7F7D7D",
    fontSize: Fonts.size.regular,
    width: "55%",
  },
  actionTypeLineStyle: {
    //borderBottomColor:'black',
    //borderBottomWidth:0.5
  },
  recordStyle: {
    fontSize: Fonts.size.input,
  },
  circleView: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "30%",
    position: "absolute",

    backgroundColor: "red",
  },
  progressVal: {
    fontSize: Fonts.size.medium,
    color: "#1d1d1d",
  },
  footerDiv: {
    width: "100%",
    minHeight: height(7),
    backgroundColor: "transparent",
    position: "absolute",
    bottom: 0,
    borderTopColor: "grey",
    borderTopWidth: 0.5,
  },
  projectText: {
    flexDirection: "column",
    width: width(45),
    justifyContent: "center",
    alignItems: "center",
  },

  actionText: {
    flexDirection: "column",
    width: width(45),
    justifyContent: "center",
    alignItems: "center",
  },
  lineIconStyle: {
    width: width(10),
    justifyContent: "center",
    alignItems: "center",
  },
  footerContainer: {
    width: "100%",
    minHeight: height(8.5),
    backgroundColor: "transparent",
    flexDirection: "row",
  },
  footerButton: {
    width: "50%",
    height: "100%",
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerButton1: {
    width: "50%",
    minHeight: height(7),
    padding: 10,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerButton2: {
    flexDirection: "column",
    minHeight: height(7),
    flex: 1,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  headerDiv: {
    width: width(50),
    minHeight: height(8),
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: width(6),
  },
  calendarDivicon: {
    width: "20%",
    minHeight: height(8.5),
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  segmentDiv: {
    width: "100%",
    minHeight: height(9),
    backgroundColor: "transparent",
    flexDirection: "row",
  },
  segmentBox2: {
    width: "40%",
    minHeight: height(7),
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    borderRightColor: "white",
    borderRightWidth: 0.5,
  },
  segmentBox1: {
    width: "30%",
    minHeight: height(7),
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    borderRightColor: "white",
    borderRightWidth: 0.5,
  },
  segmentBox: {
    width: "30%",
    minHeight: height(7),
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
  },
  activeTab: {
    color: "white",
    fontSize: 14,
    fontWeight: "bold",
  },
  activeTabCount: {
    color: "white",
    fontSize: 26,
    fontWeight: "bold",
  },
  calendarDiv: {
    width: "100%",
    backgroundColor: "white",
    borderRadius: 10,
    padding: 10,
  },
  quickModaldiv: {
    width: "100%",
    minHeight: height(30),
    maxHeight: height(50),
    backgroundColor: "white",
    borderRadius: 5,
    padding: SPACING.NORMAL,
  },
  quickheader: {
    width: "100%",
    minHeight: height(7),
    backgroundColor: "white",
    borderBottomWidth: 0.5,
    borderBottomColor: "lightgrey",
    justifyContent: "center",
    alignItems: "center",
  },
  quickBody: {
    width: "100%",
    minHeight: height(13),
    backgroundColor: "white",
    marginTop: SPACING.SMALL,
  },
  textDiv: {
    width: "100%",
    borderBottomColor: "lightgrey",
    borderBottomWidth: 0.5,
    flexDirection: "row",
  },
  quickFooter: {
    width: "100%",
    minHeight: height(7),
    backgroundColor: "white",
    borderTopWidth: 0.5,
    borderTopColor: "lightgrey",
    // justifyContent:'center',
    // alignItems:'center'
    flexDirection: "row",
  },
  btnDiv: {
    width: "50%",
    minHeight: height(7),
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  btnDiv2: {
    width: "50%",
    minHeight: height(7),
    backgroundColor: "white",
    borderLeftWidth: 0.5,
    borderLeftColor: "grey",
    justifyContent: "center",
    alignItems: "center",
  },

  dullTextOverall: {
    width: "85%",
    minHeight: height(2.5),
    fontSize: 11,
    color: "grey",
  },

  progressText: {
    fontSize: 13,
    color: "#485B9E",
  },
  searchDiv: {
    width: "100%",
    minHeight: height(5),
    backgroundColor: "white",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  dropdowndiv: {
    flex: 1,
    width: "40%",
    minHeight: height(5),
    flexDirection: "row",
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  LabelText: {
    paddingLeft: 5,
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  header: {
    width: "100%",
    minHeight: height(6.5),
    alignItems: "center",
    flexDirection: "row",
  },
  heading: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width(70),
    minHeight: height(8),
  },
  headingText: {
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  footer: {
    width: "100%",
    minHeight: height(6),
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: "lightgrey",
    borderTopWidth: 0.5,
  },
  bodyCont: {
    width: "100%",
    height: "100%",
  },
  bodyCont1: {
    width: "100%",
    height: "80%",
  },
  bodyCont2: {
    width: "100%",
    height: "100%",
  },
  projectBox: {
    flex: 1,
    flexDirection: "row",
    padding: SPACING.NORMAL,
    marginLeft: SPACING.SMALL,
    marginRight: SPACING.SMALL,
    marginBottom: 0,
    height: undefined,
    borderBottomColor: "#DEDBDB",
    borderBottomWidth: 0.5,
  },
  projectBoxStatus: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: width(24),
    padding: SPACING.NORMAL,
    position: "absolute",
    right: 0,
    paddingLeft: 5,
  },
  projectBoxContent: {
    flexDirection: "column",
    justifyContent: "flex-start",
    padding: SPACING.NORMAL,
    backgroundColor:'#fff',
    right: '4%',
  },
  apqpTypeIcon: {
    width: 20,
    height: 17,
    left: 5,
    top: 5,
    position: "absolute",
  },
  riskTypeIcon: {
    width: 20,
    height: 17,
    left: 5,
    top: 5,
    position: "absolute",
  },
  meetingTypeIcon: {
    width: 20,
    height: 17,
    left: 5,
    top: 5,
    position: "absolute",
  },
  filterCont: {
    width: "100%",
    minHeight: height(2.5),
  },
  filterBox: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  scrollViewBody: {
    height: "100%",
    backgroundColor: "transparent",
  },
  scrollTodayViewBody: {
    height: "100%",
    backgroundColor: "transparent",
  },
  renderFilterView: {
    padding: 5,
    margin: 5,
    borderRadius: 5,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "lightgrey",
  },
  renderFilterContainer: {
    width: "100%",
    height: null,
    flexDirection: "row",
    padding: 8,
    flexWrap: "wrap",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  renderFilterText: {
    fontSize: Fonts.size.medium,
    fontFamily: "OpenSans-Regular",
  },
  listItemTouchable: {
    width: "95%",
  },
  projectTitleText: {
    marginLeft: 30,
    padding: 3,
    fontSize: Fonts.size.regular,
    color: "#485B9E",
    fontFamily: "OpenSans-Regular",
  },
  projectDateText: {
    padding: 3,
    fontSize: Fonts.size.small,
    color: "#A6A6A6",
    fontFamily: "OpenSans-Regular",
  },
  projectDescriptionText: {
    padding: 3,
    fontSize: Fonts.size.medium,
    color: "#545454",
    fontFamily: "OpenSans-Regular",
  },
  listItemSeparator: {
    width: Window.width,
    height: 1,
    backgroundColor: "transparent",
  },
  todayFlashListContent: {
    paddingBottom: height(4),
  },
  refreshOnErrorContainer: {
    paddingVertical: 20,
    width: Window.width,
    minHeight: height(55),
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
  },
  refreshOnErrorButton: {
    width: "100%",
    height: null,
    justifyContent: "center",
    alignItems: "center",
  },
  refreshOnErrorText: {
    textAlign: "center",
    fontSize: Fonts.size.h5,
    color: "#21AFD5",
    fontFamily: "OpenSans-Regular",
  },
  noRecordsText: {
    alignItems: "center",
    textAlign: "center",
    fontSize: Fonts.size.h5,
    paddingTop: height(5),
    marginTop: height(6),
    fontFamily: "OpenSans-Regular",
  },
  bounceContainer: {
    paddingVertical: 20,
    width: Window.width,
    minHeight: height(55),
    flex: 1,
    marginTop: height(6),
    flexDirection: "column",
    alignItems: "center",
  },
  scrollViewBodyWithMarginTop: {
    marginTop: height(6),
  },
  footerTopBorder: {
    borderTopWidth: 1,
    borderTopColor: "lightgrey",
    marginBottom: 5,
  },
  footerMenuRow: {
    flexDirection: "row",
    paddingHorizontal: SPACING.NORMAL,
    paddingVertical: SPACING.SMALL,
  },
  footerTextActiveMedium: {
    color: "#00BAC8",
    fontSize: Fonts.size.medium,
    fontFamily: "OpenSans-Regular",
    alignItems: "center",
    textAlign: "center",
  },
  footerTextInactiveMedium: {
    color: "#848484",
    fontSize: Fonts.size.medium,
    fontFamily: "OpenSans-Regular",
    alignItems: "center",
    textAlign: "center",
  },
  footerTextActiveSmall: {
    color: "#00BAC8",
    fontSize: 12,
    fontFamily: "OpenSans-Regular",
    alignItems: "center",
    textAlign: "center",
  },
  footerTextInactiveSmall: {
    color: "#848484",
    fontSize: 12,
    fontFamily: "OpenSans-Regular",
    alignItems: "center",
    textAlign: "center",
  },
  footerIconButton: {
    justifyContent: "center",
    alignItems: "center",
    width: width(14),
    minHeight: height(4),
  },
  footerAccentText: {
    color: "#00BAC8",
  },
  footerButton1WithBorder: {
    borderLeftWidth: 0.5,
    borderLeftColor: "white",
  },
  topSpacerIos: {
    padding: SPACING.MEDIUM,
    flexDirection: "row",
  },
  topSpacerAndroid: {
    padding: SPACING.NORMAL,
    flexDirection: "row",
  },
  tabHeaderContainer: {
    width: Window.width,
    flexDirection: "row",
    minHeight: height(6),
  },
  tabHeaderItem: {
    width: Window.width / 3,
    alignItems: "center",
    justifyContent: "center",
  },
  tabTextActive: {
    fontWeight: "700",
    color: "#4ACECD",
    textAlign: "center",
    fontSize: 14,
  },
  tabTextInactive: {
    fontWeight: "400",
    color: "#888",
    textAlign: "center",
    fontSize: 14,
  },
  tabTextSmallActive: {
    fontWeight: "700",
    color: "#4ACECD",
    textAlign: "center",
    fontSize: 12,
  },
  tabTextSmallInactive: {
    fontWeight: "400",
    color: "#888",
    textAlign: "center",
    fontSize: 12,
  },
  tabIndicatorTrack: {
    width: Window.width,
    height: 2,
    backgroundColor: "#fff",
    flexDirection: "row",
  },
  tabIndicatorSpacer: {
    backgroundColor: "#0000",
    height: 2,
  },
  tabIndicator: {
    backgroundColor: "#4ACECD",
    width: Window.width / 3,
    height: 4,
  },
  tabPage: {
    width: Window.width,
  },
  modalTitleText: {
    fontSize: 20,
    color: "#61BAD0",
  },
  quickModalTitle: {
    fontSize: 22,
    color: "#61BAD0",
  },
  quickPercentageLabel: {
    paddingLeft: 5,
  },
  quickPercentageInput: {
    fontSize: 18,
  },
  quickErrorText: {
    color: "red",
  },
  quickProgressText: {
    fontSize: 16,
    color: "#31899F",
  },
  quickCancelText: {
    color: "red",
    fontSize: 18,
  },
  quickUpdateText: {
    color: "green",
    fontSize: 18,
  },
  toastStyle: {
    backgroundColor: "black",
    margin: 20,
  },
  toastText: {
    color: "white",
  },
  tabBarTextStyle: {
    fontSize: 17,
    textAlign: "center",
  },
  defaultTabUnderline: {
    backgroundColor: "#FFFFFF",
    borderBottomColor: "#FFFFFF",
  },
  defaultTabText: {
    fontSize: Fonts.size.medium,
    fontFamily: "OpenSans-Regular",
  },
  footerSpacer: {
    marginTop: height(8),
  },

  separatorSection: {
    flexDirection: "column",
    alignItems: "center",
    width: width(0.2),
    minHeight: height(5),
    borderWidth: 0,
    backgroundColor: "lightgrey",
    marginTop: SPACING.SMALL,
    marginBottom: SPACING.SMALL,
  },
  backlogo: {
    flexDirection: "row",
    backgroundColor: "transparent",
    width: width(15),
    minHeight: height(8),
    justifyContent: "center",
    alignItems: "center",
  },
  sectionHeaderContainer: {
    backgroundColor: "#fff",
    paddingBottom: SPACING.X_NORMAL,
    paddingHorizontal: SPACING.NORMAL,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignSelf: "center",
    width: "98%",
  },

  sectionHeader: {
    backgroundColor: '#1FBFD0',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: SPACING.NORMAL,
  },

  sectionHeaderText: {
    fontSize: Fonts.size.h5,
    fontWeight: "bold",
    color: '#fff',
  },

});
