import { StyleSheet, Dimensions } from "react-native";
import { Metrics, ApplicationStyles } from "../../themes";
import Fonts from "../../themes/Fonts";
import { width, height } from "react-native-dimension";
import { reduce } from "underscore";

let Window = Dimensions.get("window");

export default StyleSheet.create({
  ...ApplicationStyles.screen,
  fillcontainer: {
    flex: 1,
  },
  mainContainer: {
    flex: 1,
    width: Window.width,
    height: Window.height,
  },
  welcomeTxtView: {
    maxWidth: "70%",
    marginLeft: 5,
  },
  header: {
    width: "100%",
    height: 70,
    alignItems: "center",
    flexDirection: "row",
  },
  headerIcon: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    flexDirection: "row",
    paddingRight: 10,
  },
  headerContainer:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20, // Adjust the padding as needed
  },
  welcomeTxt: {
    fontSize: Fonts.size.h6,
    color: "white",
    fontFamily: "OpenSans-Bold",
    paddingLeft: 20,
  },
  bellIcon: {
    minWidth: 40,
    height: 40,
    marginRight: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  clockIcon: {
    minWidth: 40,
    height: 40,
    marginRight: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  bellBadge: {
    minWidth: 16,
    height: 16,
    paddingHorizontal: 4,
    borderRadius: 8,
    backgroundColor: "red",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 4,
    right: 4,
  },
  statusOuterView: {
    width: "100%",
    marginTop: 4,
    alignItems: "center",
    flexDirection: "row",
  },
  statusView: {
    flex: 1,
    height: "100%",
    marginBottom: 8,
    paddingTop: 4,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "white",
  },
  statusheaderTxt: {
    fontSize: 30,
    color: "grey",
    textAlign: "center",
    fontFamily: "OpenSans-SemiBold",
  },
  statusTxt: {
    fontSize: 16,
    color: "grey",
    textAlign: "center",
    fontFamily: "OpenSans-Regular",
  },
  vertBorder: {
    width: 1,
    height: "75%",
    backgroundColor: "lightgrey",
  },
  actionNotifyTxt: {
    fontSize: Fonts.size.h5,
    width: "100%",
    paddingVertical: 2,
    backgroundColor: "white",
    textAlign: "center",
    color: "#4ACECD",
    fontFamily: "OpenSans-SemiBold",
  },
  showMyAll: {
    backgroundColor: "lightgrey",
    paddingVertical: 6,
    width: "100%",
  },
  cardTitle: {
    paddingTop: 10,
    paddingBottom: 1,
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "white",
  },
  cardTitleTxt: {
    fontSize: 18,
    color: "grey",
    // fontWeight:'bold',
    fontFamily: "OpenSans-BoldItalic",
  },
  moreTxt: {
    fontSize: 16,
    color: "#00A2E5",
    fontFamily: "OpenSans-Regular",
  },
  cardOuterView: {
    width: "90%",
    paddingVertical: 0,
    marginLeft: "5%",
    flexDirection: "row",
  },
  borderEnabled: {
    borderBottomWidth: 0.5,
    borderBottomColor: "lightgrey",
  },
  detailsView: {
    flex: 3,
    // borderLeftColor:'green',
    borderLeftWidth: 4,
    paddingLeft: 8,
  },
  progressRound: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderColor: "lightgrey",
    borderWidth: 4,
  },
  floatingDiv: {
    position: "absolute",
    right: 20,
    bottom: 120,
    zIndex: 1000,
    justifyContent: "center",
    alignItems: "center",
  },
  floatinBtn: {
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.2)",
    alignItems: "center",
    justifyContent: "center",
    width: 60,
    height: 60,
    backgroundColor: "#00b3d6",
    // backgroundColor:'#4ACECD',
    borderRadius: 100,
    zIndex: 1000,
    elevation: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  progressVal: {
    fontSize: Fonts.size.medium,
    color: "#1d1d1d",
    fontFamily: "OpenSans-Regular",
  },
  noActivityTxt: {
    textAlign: "center",
    fontSize: Fonts.size.h6,
    marginTop: 40,
    marginBottom: 40,
    color: "grey",
    fontFamily: "OpenSans-Regular",
  },
  bgWhite: {
    backgroundColor: "white",
  },
  paddingTop5: {
    paddingTop: 5,
  },
  statusText: {
    fontSize: Fonts.size.small,
    color: "#00A2E5",
    textAlign: "center",
    fontFamily: "OpenSans-Regular",
  },
  circle: {
    marginTop: 40,
    flex: 1,
    marginLeft: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  statusTextCircle: {
    marginTop: 4,
    maxWidth: 100,
    textAlign: "center",
    fontFamily: "OpenSans-Regular",
  },
  bgCont: {
    resizeMode: "stretch",
    width: "100%",
    height: "100%",
  },
  bodyCont: {
    width: "100%",
    height: "100%",
    backgroundColor: "yellow",
  },
  headerCont: {
    width: "100%",
    height: 60,
  },
  scrollTodayViewBody: {
    marginTop: 50,
    height: "79%",
    backgroundColor: "transparent",
  },

  scrollViewBody: {
    height: "90%",
    backgroundColor: "transparent",
  },
  calendarScrollViewBody: {
    height: "100%",
    paddingTop: 50,
    backgroundColor: "transparent",
  },
  backlogo: {
    flexDirection: "row",
    backgroundColor: "transparent",
    width: width(15),
    height: 65,
    justifyContent: "center",
    alignItems: "center",
  },
  heading: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width(70),
    height: 65,
  },
  headingText: {
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  headerDiv: {
    width: width(50),
    height: 65,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 25,
  },
  rightHeader: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    right: 10,
    height: 80,
  },
  filterBox: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    // borderLeftColor:"lightgrey",
    // borderLeftWidth:0.7
  },
  filterCont: {
    width: "100%",
    height: 50,
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "lightgrey",
    marginTop: 40,
  },
  renderFilterView: {
    // width:null,
    // height:null,
    padding: 5,
    margin: 5,
    borderRadius: 5,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "lightgrey",
    // flexDirection: 'row',
    // marginLeft: 6,
    // justifyContent: 'center',
    // alignItems: 'center',
    // borderRadius: 5
  },
  projectBox: {
    flex: 1,
    flexDirection: "row",
    padding: 5,
    marginLeft: 5,
    marginRight: 5,
    marginBottom: 0,
    // borderColor: 'red',
    // borderWidth: 1,
    // borderRadius: 1,
    // shadowColor: '#000',
    // shadowOffset: {width: 0, height: 2},
    // shadowOpacity: 0.8,
    // shadowRadius: 2,
    // elevation: 1,
    height: undefined,
    borderBottomColor: "#DEDBDB",
    borderBottomWidth: 0.2,
  },
  projectBoxStatusBar: {
    flexDirection: "column",
    justifyContent: "flex-start",
    width: width(1),
  },
  projectBoxContent: {
    flexDirection: "column",
    justifyContent: "flex-start",
    width: width(90),
    padding: 5,
  },
  projectBoxStatus: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    padding: 10,
    position: "absolute",
    right: 0,
    paddingLeft: 5,
  },
  apqpTypeIcon: {
    width: 20,
    height: 17,
    left: 5,
    top: 5,
    position: "absolute",
  },
  flatListInsideView: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    height: 25,
  },
  actionTypeTextStyle: {
    color: "#7F7D7D",
    fontSize: Fonts.size.small,
  },
  listText: {
    color: "#AFAAAC",
    fontSize: Fonts.size.medium,
    padding: 2,
    marginLeft: 20,
  },
  riskTypeIcon: {
    width: 20,
    height: 19,
    left: 5,
    top: 5,
    position: "absolute",
  },
  meetingTypeIcon: {
    width: 20,
    height: 21,
    left: 5,
    top: 5,
    position: "absolute",
  },

  apqpRecentIcon: {
    width: 20,
    height: 19,
    left: 5,
    top: 5,
    position: "absolute",
  },
  flatListInsideView: {
    flexDirection: "row",
    alignItems: "center",
    // backgroundColor: 'yellow',
    height: 25,
  },
  LabelText: {
    paddingLeft: 5,
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  footerDiv: {
    width: "100%",
    height: 72,
    backgroundColor: "transparent",
    position: "absolute",
    bottom: 0,
    borderTopColor: "grey",
    borderTopWidth: 0.5,
  },
  footerContainer: {
    width: "100%",
    height: 70,
    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    flexDirection: "row",
    paddingBottom: 10,
  },
  flatList: {
    width: "100%",
    height: "100%",
    padding: 0,
    //marginBottom: 30,
  },

  popup: {
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    backgroundColor: "white",
    borderRadius: 20,
  },
});
