import { StyleSheet, Dimensions, Platform } from "react-native";
import { width, height } from "react-native-dimension";
import Fonts from "../../themes/Fonts";

const Width = Dimensions.get("window").width;
const Height = Dimensions.get("window").height;

const styles = StyleSheet.create({
  mainContainer: {
    width: "100%",
    height: "100%",
  },
  containerRecent: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: Width,
    height: 50,
    marginTop: 0,
  },
  containerScroll: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: Width,
    height: 45,
    marginTop: 0,
  },
  calendarContainer: {
    width: Width,
    position: "absolute",
    zIndex: 1000,
    top: height(6),
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "stretch",
  },
  filterDiv: {
    flex: 1,
    /*width:Width/5,*/
    backgroundColor: "white",
    padding: 5,
  },
  textFontStyle: {
    fontSize: Fonts.size.medium,
    backgroundColor: "white",
    color: "grey",
    margin: 2,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 5,
    paddingBottom: 5,
    borderRadius: 15,
    textAlign: "center",
    shadowColor: "#4b4b4b",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    overflow: "hidden",
    borderWidth: 0.5,
    borderColor: "#E7EBEC",
  },
  textFontStyleSelected: {
    fontSize: Fonts.size.medium,
    backgroundColor: "#DDDCDA",
    color: "grey",
    margin: 2,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 5,
    paddingBottom: 5,
    borderRadius: 15,
    textAlign: "center",
    shadowColor: "#4b4b4b",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    overflow: "hidden",
    borderWidth: 0.5,
    borderColor: "#E7EBEC",
  },
  checkBox: {
    /* position: 'absolute',
    top:height(5),
    padding: 2,
    margin: 2,
    marginBottom: 0,
    flexDirection: 'row' */
  },
  radioScroll: {
    position: "absolute",
    top: 40,
    padding: 2,
    margin: 2,
    marginBottom: 0,
    flexDirection: "row",
    width: "100%",
  },
  checkBoxnone: {
    display: "none",
  },
  dropBox: {
    position: "absolute",
    top: height(2),
    right: 20,
    width: width(30),
    marginTop: 25,
  },
  dateRange: {
    fontSize: Fonts.size.medium,
    color: "grey",
    margin: 5,
    padding: 5,
    marginBottom: 0,
    textAlign: "center",
  },
  flexDirection: { flexDirection: "row" },
  checkBoxText: {
    fontSize: 16,
    marginTop: 15,
    width: "78%",
    right: 10,
    fontFamily: "OpenSans-Regular",
  },

  calendarModal: {
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    backgroundColor: "white",
    borderRadius: 20,
  },
  modalBody: {
    width: width(90),
    height: height(65),
    backgroundColor: "white",
    borderRadius: 8,
  },
  modalheading: {
    width: "100%",
    height: "10%",
    backgroundColor: "transparent",
    position: "absolute",
    borderBottomColor: "lightgrey",
    borderBottomWidth: 0.8,
    justifyContent: "center",
    alignItems: "center",
    top: height(2),
  },
  modalfooter: {
    width: "100%",
    height: "10%",
    backgroundColor: "grey",
    position: "absolute",
    borderBottomColor: "lightgrey",
    borderBottomWidth: 0.8,
    justifyContent: "center",
    alignItems: "center",
    bottom: height(2),
  },
  scrollView: {
    marginTop: height(10),
    height: "80%",
    width: "100%",
    backgroundColor: "transparent",
  },
  LabelText: {
    paddingLeft: 5,
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  header: {
    width: "100%",
    height: 50,
    alignItems: "center",
    flexDirection: "row",
  },
  headerDiv: {
    width: width(25),
    height: 65,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 20,
  },
  heading: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width(70),
    height: 65,
  },
  headingText: {
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  footer: {
    width: "100%",
    height: 48,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: "lightgrey",
    borderTopWidth: 0.5,
  },
  cancelView: {
    width: "86%",
    marginTop: 10,
    paddingVertical: 10,
    marginHorizontal: "7%",
    borderWidth: 1,
    backgroundColor: "#FEF0F2",
    borderColor: "lightgrey",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 3,
    bottom: 10,
    // position:'absolute'
  },
  searchView: {
    width: "86%",
    marginTop: 20,
    marginHorizontal: "7%",
    borderWidth: 1,
    borderColor: "grey",
    borderRadius: 3,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: Platform.OS === "ios" ? 10 : null,
  },
  applyView: {
    width: "86%",
    marginTop: 10,
    marginBottom: 10,
    paddingVertical: 10,
    marginHorizontal: "7%",
    borderWidth: 1,
    backgroundColor: "#FEF0F2",
    borderColor: "lightgrey",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 3,
  },
  applyText: {
    fontSize: 16,
    textAlign: "center",
    fontFamily: "OpenSans-Regular",
  },
  searchText: {
    fontSize: 20,
  },
  date: {
    width: "100%",
    paddingVertical: 20,
    paddingLeft: 20,
    borderTopColor: "lightgrey",
    borderTopWidth: 1,
    flexDirection: "row",
    marginTop: 10,
  },
  dateview: {
    width: "40%",
    alignItems: "flex-end",
  },
  iconView: {
    padding: 20,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#ffffff",
  },
  backLogo: {
    flexDirection: "row",
    backgroundColor: "transparent",
    width: width(15),
    height: 65,
    justifyContent: "center",
    alignItems: "center",
  },
});

export default styles;
