import { StyleSheet, Dimensions } from "react-native";
import { Metrics, ApplicationStyles } from "../../themes";
import Fonts from "../../themes/Fonts";
import { width, height } from "react-native-dimension";
import { SPACING } from "constants/theme-constants";

let Window = Dimensions.get("window");

export default StyleSheet.create({
  ...ApplicationStyles.screen,
  topSpacerIos: {
    padding: SPACING.MEDIUM,
    flexDirection: "row",
  },
  topSpacerAndroid: {
    padding: SPACING.NORMAL,
    flexDirection: "row",
  },
  fillcontainer: {
    flex: 1,
  },
  scrollTodayViewBody: {
    flex: 1,
  },
  mainContainer: {
    flex: 1,
    width: "100%",
  },
  bgImage: {
    width: Window.width,
    height: "140%",
    resizeMode: "cover",
  },
  apqpTextStyle: {
    fontSize: 24,
    color: "white",
  },
  buttonStyles: {
    borderTopColor: "transparent",
    flexDirection: "column",
  },
  buttonTouchableStyle: {
    width: 100,
    height: 30,
    borderRadius: 50,
    borderWidth: 0.5,
    elevation: 1,
    borderColor: "lightgrey",
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#AFAAAC",
  },
  buttonView: {
    paddingLeft: 10,
    borderColor: "#AFAAAC",
  },
  listView: {
    flexDirection: "row",
    padding: 2,
  },
  listText: {
    color: "black",
    fontSize: Fonts.size.regular,
    fontFamily: "OpenSans-Regular",
    padding: 2,
  },
  listNextText: {
    fontSize: Fonts.size.regular,
    fontFamily: "OpenSans-Regular",
    padding: 2,
  },
  flatList: {
    flex: 1,
    width: "100%",
    padding: 5,
    //marginBottom: 30,
  },
  // flatListView: {
  //   flex: 1,
  //   padding: 3,
  // },
  flatListTouchableView: {
    width: "100%",
    //flex: 5,
    borderRadius: 1,
    borderWidth: 0.5,
    elevation: 3,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: 6,
    borderLeftWidth: 5,
    flexDirection: "row",
  },

  // flatListInsideView: {
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   backgroundColor: 'white',
  //   height: 25
  // },

  footerDiv: {
    width: "100%",
    height: 60,
    backgroundColor: "transparent",
    position: "absolute",
    bottom: 0,
  },
  projectText: {
    flexDirection: "column",
    width: width(45),
    justifyContent: "center",
    alignItems: "center",
  },

  actionText: {
    flexDirection: "column",
    width: width(45),
    justifyContent: "center",
    alignItems: "center",
  },
  lineIconStyle: {
    width: width(10),
    justifyContent: "center",
    alignItems: "center",
  },
  footerContainer: {
    width: "100%",
    height: 70,
    backgroundColor: "transparent",
    flexDirection: "row",
  },
  footerButton: {
    width: "50%",
    height: "100%",
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerButton1: {
    width: "50%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerButton2: {
    width: "50%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    borderLeftColor: "white",
    borderLeftWidth: 0.5,
  },

  // headerTextDiv: {
  //   width: '80%',
  //   height: 70,
  //   justifyContent: 'center',
  //   alignItems: 'center'
  // },
  calendarDiv: {
    width: "10%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
  },

  dullTextOverall: {
    width: "30%",
    height: 20,
    fontSize: 13,
    color: "grey",
    paddingBottom: 10,
  },
  NumberTextOverall: {
    width: "20%",
    height: 28,
    fontSize: 28,
    fontWeight: "bold",
    color: "green",
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 10,
  },

  wrapper: {
    /*flex: 1,*/
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    backgroundColor: "transparent",
    width: "100%",
    height: 70,
    top: 120,
    borderBottomColor: "lightgrey",
    borderBottomWidth: 1,
    paddingTop: 5,
  },

  boxView: {
    width: "98%",
    height: 130,
    borderWidth: 0.5,
    borderRadius: 3,
    borderLeftWidth: 5,
    borderLeftColor: "green",
    //backgroundColor:'yellow'
  },

  flatListWholeView: {
    width: window.width,
    height: 162,
    //backgroundColor:'yellow',
    padding: 5,
    //paddingBottom: 8,
    //borderWidth: 0.5,
    //borderColor:'lightgrey',
    //borderRadius: 5,
    //elevation: 0,
    // borderLeftWidth: 5,
    // borderLeftColor: "green",
    borderBottomWidth: 0.5,
    borderBottomColor: "lightgrey",
  },

  bgImage: {
    width: Window.width,
    height: "140%",
    resizeMode: "cover",
  },
  apqpTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    //color:'black',
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  apqpTextStyle: {
    fontSize: 24,
    color: "white",
  },
  segmentControlTabView: {
    position: "absolute",
    height: "100%",
    width: "80%",
    //borderColor:'black',
    marginTop: 50,
    marginLeft: 20,
    paddingBottom: 15,
  },
  segmentControlTab: {
    borderColor: "white",
    height: 60,
  },
  activeTabStyle: {
    backgroundColor: "white",
  },
  activeTabTextStyle: {
    color: "#00b1cf",
  },
  tabTextStyle: {
    color: "black",
    fontSize: Fonts.size.small,
  },
  tabsContainerStyle: {
    width: Metrics.screenWidth,
  },
  buttonTouchableStyle: {
    width: 100,
    height: 30,
    borderRadius: 50,
    borderWidth: 0.5,
    elevation: 1,
    borderColor: "lightgrey",
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#AFAAAC",
  },
  flatListView: {
    flex: 1,
    padding: 3,
  },
  flatListTouchableView: {
    width: "100%",
    //flex: 5,
    borderRadius: 1,
    borderWidth: 0.5,
    elevation: 3,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: 6,
    borderLeftWidth: 5,
    flexDirection: "row",
  },
  flatListInsideView: {
    flexDirection: "row",
    alignItems: "center",
    //backgroundColor: 'yellow',
    height: 25,
    marginLeft:'3%'
  },

  floattext: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    padding: 10,
    position: "absolute",
    right: 0,
    paddingLeft: 5,
  },

  circle: {
    marginTop: 60,
    flex: 1,
    marginLeft: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  actionTypeTextStylecb: {
    color: "#1FBFD0",
    fontSize: Fonts.size.regular,
    fontFamily: "OpenSans-Regular",
  },
  actionTypeTextStyle: {
    color: "#7F7D7D",
    fontSize: Fonts.size.regular,
    fontFamily: "OpenSans-Regular",
  },
  dateTextStyle: {
    color: "#7F7D7D",
    fontSize: Fonts.size.medium,
  },
  actionTypeTextStyleDesc: {
    color: "#7F7D7D",
    fontSize: Fonts.size.regular,
    width: "55%",
  },
  actionTypeLineStyle: {
    //borderBottomColor:'black',
    //borderBottomWidth:0.5
  },
  recordStyle: {
    fontSize: Fonts.size.regular,
  },
  circleView: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "30%",
    position: "absolute",

    backgroundColor: "red",
  },
  progressVal: {
    fontSize: Fonts.size.medium,
    color: "#1d1d1d",
  },
  footerDiv: {
    width: "100%",
    height: 60,
    backgroundColor: "transparent",
    position: "absolute",
    borderTopWidth: 0.5,
    borderTopColor: "lightgrey",
    bottom: 0,
  },
  projectText: {
    flexDirection: "column",
    width: width(45),
    justifyContent: "center",
    alignItems: "center",
  },

  actionText: {
    flexDirection: "column",
    width: width(45),
    justifyContent: "center",
    alignItems: "center",
  },
  lineIconStyle: {
    width: width(10),
    justifyContent: "center",
    alignItems: "center",
  },
  footerContainer: {
    flexDirection: "column",
    // width: width(32),
    // width:'25%',
    height: 60,
    flex: 1,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    // textAlign: 'center',
    // color: 'white',
    backgroundColor: "transparent",
  },
  footerButton: {
    width: "50%",
    height: "100%",
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerButton1: {
    width: "50%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
    //flexDirection: "column",
  },
  footerButton2: {
    width: "50%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    borderLeftColor: "white",
    borderLeftWidth: 0.5,
  },
  headerTextDiv: {
    width: "80%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
  },
  calendarDiv: {
    width: "10%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
  },

  progressText: {
    fontSize: 13,
    color: "#485B9E",
  },
  progressTextOverall: {
    width: "85%",
    height: 20,
    fontSize: 13,
    color: "#485B9E",
  },
  dropdowndiv: {
    flex: 1,
    width: "40%",
    height: 40,
    flexDirection: "row",
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  // dullTextOverall: {
  //   width: '85%',
  //   height: 20,
  //   fontSize: 13,
  //   color: 'grey',
  // },
  searchDiv: {
    width: "100%",
    height: 40,
    backgroundColor: "white",
    marginTop: 10,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  header: {
    width: "100%",
    height: 70,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    borderBottomColor: "lightgrey",
    borderBottomWidth: 0.5,
  },
  calendarDiv2: {
    width: "100%",
    backgroundColor: "white",
    borderRadius: 10,
    padding: 10,
  },
  footer: {
    width: "100%",
    height: 55,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: "lightgrey",
    borderTopWidth: 0.5,
  },

  header: {
    width: "100%",
    height: 60,
    alignItems: "center",
    flexDirection: "row",
  },
  headerDiv: {
    width: width(50),
    height: 65,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 25,
  },
  heading: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width(70),
    height: 65,
  },
  headingText: {
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  LabelText: {
    paddingLeft: 5,
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  backLogo: {
    flexDirection: "row",
    backgroundColor: "transparent",
    width: width(15),
    height: 65,
    justifyContent: "center",
    alignItems: "center",
  },

  filterCont: {
    width: "100%",
    height: 60,
    flexDirection: "row",
    borderBottomWidth: 0,
    borderBottomColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 0,
    paddingHorizontal: SPACING.NORMAL,
    paddingVertical: SPACING.SMALL,
  },
  searchContainer: {
    flex: 1,
    height: 46,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E6E6E6",
    paddingHorizontal: SPACING.NORMAL,
    flexDirection: "row",
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    paddingLeft: SPACING.SMALL,
    fontSize: 16,
    color: "#4A4A4A",
    fontFamily: "OpenSans-Regular",
  },
  searchClearButton: {
    paddingLeft: SPACING.SMALL,
    justifyContent: "center",
    alignItems: "center",
  },
  searchCalendarButton: {
    paddingLeft: SPACING.SMALL,
    justifyContent: "center",
    alignItems: "center",
  },
  filterLabelText: {
    fontSize: Fonts.size.medium,
    color: "#89888A",
    paddingLeft: 5,
    fontFamily: "OpenSans-Regular",
  },
  dropdownContainer: {
    flex: 2,
  },
  dropdownInnerContainer: {
    flex: 1,
  },
  dropdownItemText: {
    fontFamily: "OpenSans-Regular",
  },
  sortToggleButton: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 5,
  },
  renderFilterContainer: {
    width: "100%",
    height: null,
    flexDirection: "row",
    padding: 8,
    flexWrap: "wrap",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  renderFilterText: {
    fontSize: Fonts.size.medium,
    fontFamily: "OpenSans-Regular",
  },
  noRecordsText: {
    width: Window.width,
    height: height(100) - 213,
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    fontSize: Fonts.size.h5,
    paddingTop: 40,
    fontFamily: "OpenSans-Regular",
  },
  bounceContainer: {
    paddingVertical: 20,
    width: "100%",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  footerHomeButton: {
    justifyContent: "center",
    alignItems: "center",
    width: 50,
    height: 25,
  },
  footerHomeText: {
    color: "#00BAC8",
  },
  calendarTitleText: {
    fontSize: 20,
    color: "#61BAD0",
  },
  filterBox: {
    flex: 1,
    height:50,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    // borderLeftColor:"lightgrey",
    // borderLeftWidth:0.7
  },
  renderFilterView: {
    // width:null,
    // height:null,
    padding: 5,
    margin: 5,
    borderRadius: 5,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "lightgrey",
    // flexDirection: 'row',
    // marginLeft: 6,
    // justifyContent: 'center',
    // alignItems: 'center',
    // borderRadius: 5
  },
  emptyStateContainer1: {
    width: "92%",
    height: 160,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginTop: 100,
    backgroundColor: "#FFFFFF",
  },
});
