import { StyleSheet, Dimensions } from "react-native";
import { Metrics, ApplicationStyles } from "../../themes";
import Fonts from "../../themes/Fonts";
import { width, height } from "react-native-dimension";
// import { android15HeaderPadding, android15FooterPadding, android15FooterOffset } from  '../../../auditPro/Themes/AndroidInsets';  

let Window = Dimensions.get("window");

export default StyleSheet.create({
  ...ApplicationStyles.screen,
  fillcontainer: {
    flex: 1,
  },
  LoginButton: {
    width: 100,
    height: 50,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
  },
  buttonText: {
    textAlign: "center",
    //margin: 10,
    color: "#ffffff",
    backgroundColor: "transparent",
    fontSize: Fonts.size.input,
  },
  mainContainer: {
    flex: 1,
    width: Window.width,
    height: Window.height,
  },
  bgImage: {
    width: "100%",
    height: 65,
    resizeMode: "stretch",
  },
  bgImageFooter: {
    width: "100%",
    height: 65,
    resizeMode: "stretch",
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  progressTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  deliveryTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    // color: 'black',
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  deliveryTextStyle: {
    color: "#FFFFFF",
    fontSize: Fonts.size.h4,
  },
  progressTextStyle: {
    fontSize: Fonts.size.h4,
  },
  heading: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width(70),
    height: 65,
  },

  flatListWholeView: {
    width: "100%",
    height: "83%",
    backgroundColor: "white",
    position: "absolute",
    padding: 3,
  },
  flatList: {
    width: "100%",
    height: "100%",
    //flex:4,
    //flexDirection:'column',
    position: "absolute",
    marginTop: 60,
    padding: 8,
  },
  flatListView: {
    flex: 1,
    padding: 3,
  },
  flatListTouchableView: {
    width: "100%",
    flex: 4,
    borderRadius: 1,
    borderWidth: 0.5,
    elevation: 3,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: 2,
    borderLeftWidth: 5,
    borderLeftColor: "green",
    flexDirection: "row",
  },
  listText: {
    color: "#AFAAAC",
    fontSize: Fonts.size.regular,
    padding: 6,
    textAlignVertical: "top",
  },

  flatListFullView: {
    width: "100%",
    height: 165,
    //backgroundColor:'yellow',
    borderWidth: 0.5,
    borderLeftWidth: 5,
    borderLeftColor: "green",
    padding: 4,
    borderRadius: 1,
  },

  flatListFullSideView: {
    flex: 1,
    flexDirection: "row",
    padding: 10,
    marginLeft: 5,
    marginRight: 8,
    marginBottom: 0,
    // borderWidth: 1,
    // borderColor: "red",
    height: undefined,
    borderBottomColor: "#DEDBDB",
    borderBottomWidth: 0.5,
  },

  flatListInsideView: {
    flexDirection: "row",
    alignItems: "center",
  },

  textHeader: {
    flexDirection: "row",
    alignItems: "center",
  },

  deliveryTypeTextStyle: {
    color: "#7F7D7D",
    fontSize: Fonts.size.regular,
    //width: "85%",
  },
  deliveryTypeTextStyleHours: {
    color: "green",
    fontSize: Fonts.size.regular,
    //width: "85%",
  },
  deliveryTypeTextStylePercent: {
    color: "#485B9E",
    fontSize: Fonts.size.regular,
    width: "85%",
  },
  buttonTextDel: {
    textAlign: "center",
    fontSize: Fonts.size.input,
    color: "white",
  },
  buttonText: {
    textAlign: "center",
    fontSize: Fonts.size.input,
  },
  addTextStyle: {
    color: "#8B8D8C",
    fontSize: Fonts.size.regular,
  },
  iconsWholeView: {
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  editIconView: {
    width: "60%",
    justifyContent: "center",
    alignItems: "center",
  },

  deleteIconView: {
    //height:'50%',
    justifyContent: "center",
    alignItems: "center",
  },
  editTextStyle: {
    color: "#7F7D7D",
  },
  deleteTextStyle: {
    color: "#7F7D7D",
  },
  footer: {
    bottom: 0,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width(100),
    backgroundColor: "transparent",
    height: 65,
    zIndex: 3000,
  },
  apqpTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    //color:'black',
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  backLogo: {
    flexDirection: "row",
    backgroundColor: "transparent",
    width: width(15),
    height: 65,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTextDiv: {
    width: "70%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
  },
  apqpTextStyle: {
    fontSize: 24,
    color: "white",
  },
  footerContainer: {
    width: "100%",
    height: 70,
    backgroundColor: "transparent",
    flexDirection: "row",
    // marginBottom: 20 + android15FooterPadding,
  },
  footerButton: {
    width: "50%",
    height: "100%",
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerButton1: {
    width: "100%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerButton2: {
    width: "50%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    borderLeftColor: "white",
    borderLeftWidth: 0.5,
  },
  footerDiv: {
    width: "100%",
    height: 60,
    backgroundColor: "white",
    // borderTopColor: "#00BAC8",
    // borderTopWidth: 0.5,
    position: "absolute",
    // // bottom: 20 + android15FooterPadding,
    bottom: 0,
    // borderTopColor: "lightgrey",
    // borderTopWidth: 0.5,
  },
  footerMenuItem: {
    flexDirection: "column",
    // width: width(32),
    // width:'25%',
    height: 60,
    flex: 1,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    // textAlign: 'center',
    // color: 'white',
    backgroundColor: "transparent",
  },
  LabelText: {
    paddingLeft: 5,
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  header: {
    width: "100%",
    height: 50,
    alignItems: "center",
    flexDirection: "row",
  },
  headerDiv: {
    width: width(25),
    height: 65,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 25,
  },
  headingText: {
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  separatorSection: {
    flexDirection: "column",
    alignItems: "center",
    width: width(0.2),
    height: 40,
    borderWidth: 0,
    backgroundColor: "lightgrey",
    marginTop: 10,
    marginBottom: 10,
  },
});
