import { StyleSheet, Dimensions } from "react-native";
import { Metrics, ApplicationStyles } from "../../themes";
import Fonts from "../../themes/Fonts";
import { width, height } from "react-native-dimension";
// import { android15FooterPadding } from "../../../auditPro/Themes/AndroidInsets";

let Window = Dimensions.get("window");

export default StyleSheet.create({
  ...ApplicationStyles.screen,
  fillcontainer: {
    flex: 1,
  },
  mainContainer: {
    flex: 1,
    width: Window.width,
    height: Window.height,
  },
  textHeader: {
    flexDirection: "row",
    alignItems: "center",
  },

  bgImage: {
    width: "100%",
    height: 65,
    resizeMode: "stretch",
  },
  bgImageFooter: {
    width: "100%",
    height: 65,
    resizeMode: "stretch",
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  check: {
    position: "absolute",
    height: "85%",
    width: "10%",
    backgroundColor: "transparent",
    right: 0,
    justifyContent: "center",
    alignItems: "center",
  },

  endDatecheck: {
    position: "absolute",
    height: "35%",
    width: "10%",
    backgroundColor: "transparent",
    right: 0,
    justifyContent: "center",
    alignItems: "center",
  },

  progressTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  deliveryTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    // color: 'black',
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  deliveryTextStyle: {
    color: "#FFFFFF",
    fontSize: Fonts.size.h4,
  },
  progressTextStyle: {
    fontSize: Fonts.size.h4,
  },

  flatListWholeView: {
    width: "100%",
    height: "81%",
    position: "absolute",
    marginTop: 50,
    padding: 8,
    flexDirection: "column",
    marginBottom: 10,
    marginLeft: '3%',
  },

  apqpTextStyle: {
    fontSize: 24,
    color: "white",
  },
  footerDiv: {
    width: "100%",
    height: 60,
    backgroundColor: "transparent",
    position: "absolute",
    // bottom: 20 + android15FooterPadding ,
    bottom: 0,
    // borderTopColor: "lightgrey",
    // borderTopWidth: 0.5,
  },
  footerContainer: {
    width: "100%",
    height: 70,
    backgroundColor: "transparent",
    flexDirection: "row",
  },
  footerButton: {
    width: "50%",
    height: "100%",
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerContainer: {
    width: "100%",
    height: 70,
    backgroundColor: "transparent",
    flexDirection: "row",
  },
  footerButton1: {
    width: "100%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerButton11: {
    width: "100%",
    height: 70,
    justifyContent: "center",
    flexDirection: 'row',
    alignItems: "center",
  },
  vertBorder: {
    width: 1,
    height: "75%",
    backgroundColor: "lightgrey",
  },
  footerButton2: {
    width: "50%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    borderLeftColor: "white",
    borderLeftWidth: 0.5,
  },

  apqpTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    //color:'black',
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  backLogo: {
    flexDirection: "row",
    backgroundColor: "transparent",
    width: width(15),
    height: 65,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTextDiv: {
    width: "70%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
  },

  circleView: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    padding: 10,
    position: "absolute",
    right: 0,
    paddingLeft: 2,
  },
  progressVal: {
    fontSize: Fonts.size.medium,
    color: "#1d1d1d",
  },
  completedTextStyle: {
    fontSize: Fonts.size.regular,
    padding: 2,
    color: "black",
  },
  startDateTextStyle: {
    fontSize: Fonts.size.medium,
    padding: 2,
  },
  endDateTextStyle: {
    fontSize: Fonts.size.medium,
    padding: 2,
  },
  actualHoursTextStyle: {
    fontSize: Fonts.size.medium,
    padding: 2,
  },
  remarksTextStyle: {
    fontSize: Fonts.size.medium,
    padding: 6,
  },
  textInputStyle: {
    borderBottomWidth: 0.5,
    fontSize: Fonts.size.medium,
  },

  sectionTop: {
    backgroundColor: "white",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    borderBottomWidth: 0.5,
    borderBottomColor: "lightgrey",
    padding: 10,
  },
  sectionContent: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  boxHeader: {
    width: "100%",
    color: "#A6A6A6",
    fontSize: Fonts.size.medium,
  },
  boxContent: {
    width: "100%",
    color: "#485B9E",
    fontSize: Fonts.size.regular,
  },
  div1: {
    width: Window.width,
    //height:height(10),
    backgroundColor: "transparent",
    marginTop: 10,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  input02: {
    backgroundColor: "transparent",
    width: "90%",
    height: "90%",
  },
  placeholderT1: {
    fontSize: Fonts.size.regular,
    borderBottomColor: "lightgrey",
    borderBottomWidth: 0.5,
  },
  placeholderT1Label: {
    fontSize: Fonts.size.regular,
    paddingTop: 5,
    borderBottomColor: "lightgrey",
    borderBottomWidth: 0.5,
  },
  placeholderTextStyle: {
    padding: 0,
    margin: 0,
    fontSize: Fonts.size.small,
    color: "#A6A6A6",
  },
  remarkBoxStyle: {
    borderBottomWidth: 0.8,
    width: "99%",
    height: "40%",
    borderWidth: 0.6,
    borderRadius: 10,
  },
  sec1: {
    width: "100%",
    height: 75,
    marginLeft: '1%',
  },
  remark: {
    width: "100%",
    marginLeft: '1%',
  },
  calendarDiv: {
    width: "100%",
    height: 500,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 10,
  },
  LabelText: {
    paddingLeft: 5,
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  header: {
    width: "100%",
    height: 50,
    alignItems: "center",
    flexDirection: "row",
  },
  headerDiv: {
    width: width(25),
    height: 65,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 25,
  },
  heading: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width(70),
    height: 65,
  },
  headingText: {
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  footer: {
    width: "100%",
    height: 48,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: "lightgrey",
    borderTopWidth: 0.5,
  },
  listText: {
    color: "black",
    fontSize: Fonts.size.regular,
    padding: 6,
    textAlignVertical: "top",
  },
  roundView: {
    position: "absolute",
    //paddingTop: 10,
    top: 5,
    height: 40,
    //textAlign: "right",
    width: 40,
    right: '2%',
    borderRadius: 40,
    borderColor: "#00BAC8",
    borderWidth: 0.7,
    backgroundColor: "#00BAC8",
    justifyContent: "center",
    alignItems: "center",
  },
});
