import { StyleSheet, Dimensions } from "react-native";
import { Metrics, ApplicationStyles } from "../../themes";
import Fonts from "../../themes/Fonts";
import { width, height } from "react-native-dimension";

let Window = Dimensions.get("window");

export default StyleSheet.create({
  ...ApplicationStyles.screen,
  fillcontainer: {
    flex: 1,
  },
  mainContainer: {
    flex: 1,
    width: Window.width,
    height: Window.height,
  },
  bgImage: {
    width: Window.width,
    height: "140%",
    resizeMode: "cover",
  },
  apqpTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    //color:'black',
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  apqpTextStyle: {
    fontSize: 24,
    color: "white",
  },
  segmentControlTabView: {
    position: "absolute",
    height: "100%",
    width: "80%",
    //borderColor:'black',
    marginTop: 50,
    marginLeft: 20,
    paddingBottom: 15,
  },
  segmentControlTab: {
    borderColor: "white",
    height: 60,
  },
  activeTabStyle: {
    backgroundColor: "white",
  },
  activeTabTextStyle: {
    color: "#00b1cf",
  },
  tabTextStyle: {
    color: "black",
    fontSize: Fonts.size.small,
  },
  tabsContainerStyle: {
    width: Metrics.screenWidth,
  },
  buttonStyles: {
    borderTopColor: "transparent",
    flexDirection: "column",
  },
  buttonTouchableStyle: {
    width: 100,
    height: 30,
    borderRadius: 50,
    borderWidth: 0.5,
    elevation: 1,
    borderColor: "lightgrey",
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#AFAAAC",
  },
  buttonView: {
    paddingLeft: 10,
    borderColor: "#AFAAAC",
  },
  listText: {
    color: "#545454",
    fontSize: Fonts.size.medium,
    padding: 3,
  },

  flatList: {
    width: Window.width,
    height: "85%",
    padding: 5,
    //backgroundColor: "yellow",
    marginBottom: 30,
  },
  flatListTouchableView: {
    flex: 1,
    flexDirection: "row",
    padding: 5,
    marginLeft: 5,
    marginRight: 5,
    // borderColor: 'red',
    // borderWidth: 1,
    // borderRadius: 1,
    // shadowColor: '#000',
    // shadowOffset: {width: 0, height: 2},
    // shadowOpacity: 0.8,
    // shadowRadius: 2,
    // elevation: 1,
    height: undefined,
    borderBottomColor: "lightgrey",
    borderBottomWidth: 0.3,
  },
  flatListInsideView: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    height: 25,
  },
  actionTypeTextStylecb: {
    color: "#485B9E",
    fontSize: Fonts.size.input,
  },
  actionTypeTextStyle: {
    color: "#7F7D7D",
    fontSize: Fonts.size.regular,
  },
  dateTextStyle: {
    color: "#7F7D7D",
    fontSize: Fonts.size.medium,
  },
  actionTypeTextStyleDesc: {
    color: "#7F7D7D",
    fontSize: Fonts.size.regular,
    width: "55%",
  },
  actionTypeLineStyle: {
    //borderBottomColor:'black',
    //borderBottomWidth:0.5
  },
  recordStyle: {
    fontSize: Fonts.size.input,
  },
  circleView: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "30%",
    position: "absolute",

    backgroundColor: "red",
  },
  progressVal: {
    fontSize: Fonts.size.medium,
    color: "#1d1d1d",
  },
  footerDiv: {
    width: "100%",
    height: 60,
    backgroundColor: "transparent",
    position: "absolute",
    bottom: 0,
    borderTopColor: "lightgrey",
    borderTopWidth: 0.5,
  },
  projectText: {
    flexDirection: "column",
    width: width(45),
    justifyContent: "center",
    alignItems: "center",
  },

  actionText: {
    flexDirection: "column",
    width: width(45),
    justifyContent: "center",
    alignItems: "center",
  },
  lineIconStyle: {
    width: width(10),
    justifyContent: "center",
    alignItems: "center",
  },
  footerContainer: {
    width: "100%",
    height: 70,
    backgroundColor: "transparent",
    flexDirection: "row",
  },
  footerButton: {
    width: "50%",
    height: "100%",
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  flatListStyle: {
    width: "100%",
    height: "100%",
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    marginBottom:60,
  },
  footerButton1: {
    width: "50%",
    height: 60,
    padding: 10,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  footerButton2: {
    flexDirection: "column",
    // width: width(32),
    // width:'25%',
    height: 60,
    flex: 1,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    // textAlign: 'center',
    // color: 'white',
    backgroundColor: "transparent",
  },
  backLogo: {
    flexDirection: "row",
    backgroundColor: "transparent",
    width: width(15),
    height: 65,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTextDiv: {
    width: "80%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 25,
  },
  calendarDiv: {
    width: "10%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
  },

  progressText: {
    fontSize: 13,
    color: "#485B9E",
  },
  progressTextOverall: {
    width: "85%",
    height: 20,
    fontSize: 13,
    color: "#485B9E",
  },
  dullTextOverall: {
    width: "85%",
    height: 20,
    fontSize: 13,
    color: "grey",
  },
  dropdowndiv: {
    flex: 1,
    width: "40%",
    height: 40,
    flexDirection: "row",
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  searchDiv: {
    width: "100%",
    height: 40,
    backgroundColor: "white",
    marginTop: 10,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  calendarDiv2: {
    width: "100%",
    backgroundColor: "white",
    borderRadius: 10,
    padding: 10,
  },
  header: {
    width: "100%",
    height: 60,
    alignItems: "center",
    flexDirection: "row",
  },
  footer: {
    width: "100%",
    height: 55,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: "lightgrey",
    borderTopWidth: 0.5,
  },
  bodyCont: {
    width: "100%",
    height: "83%",
  },
  projectBox: {
    flex: 1,
    flexDirection: "row",
    padding: 10,
    marginLeft: 5,
    marginRight: 5,
    marginBottom: 0,
    // borderColor: 'red',
    // borderWidth: 1,
    // borderRadius: 1,
    // shadowColor: '#000',
    // shadowOffset: {width: 0, height: 2},
    // shadowOpacity: 0.8,
    // shadowRadius: 2,
    // elevation: 1,
    height: undefined,
    borderBottomColor: "#DEDBDB",
    borderBottomWidth: 0.7,
  },
  projectBoxStatus: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    padding: 10,
    position: "absolute",
    right: 0,
    paddingLeft: 0,
  },
  projectBoxContent: {
    flexDirection: "column",
    justifyContent: "flex-start",
    //width: width(75),
    padding: 0,
  },
  apqpTypeIcon: {
    width: 20,
    height: 17,
    left: 5,
    top: 5,
    position: "absolute",
  },
  filterCont: {
    width: "100%",
    height: 60,
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "grey",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 0,
  },
  filterBox: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    // borderLeftColor:"lightgrey",
    // borderLeftWidth:0.7
  },
  scrollViewBody: {
    height: "100%",
    backgroundColor: "transparent",
  },
  headerDiv: {
    width: width(50),
    height: 70,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 25,
  },

  //   headerDiv: {
  //     width: "100%",
  //     height: 70,
  //     backgroundColor: "white",
  //     justifyContent: "center",
  //     alignItems: "center",
  //     borderBottomColor: "lightgrey",
  //     borderBottomWidth: 0.5,
  // },
  
  LabelText: {
    paddingLeft: 5,
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  heading: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width(70),
    height: 65,
  },
  headingText: {
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  // flatListWholeView: {
  //   width: "100%",
  //   height: "100%",
  //   backgroundColor: "white",
  //   position: "absolute",
  //   marginTop: 60,
  //   padding: 4,
  // },
  flatListWholeView: {
    width: window.width,
    height: 130,
    //backgroundColor:'yellow',
    padding: 5,
    marginBottom: 5,
  },

  quickModaldiv: {
    width: "100%",
    height: 250,
    backgroundColor: "white",
    borderRadius: 5,
    padding: 10,
  },
  quickheader: {
    width: "100%",
    height: 60,
    backgroundColor: "white",
    borderBottomWidth: 0.5,
    borderBottomColor: "lightgrey",
    justifyContent: "center",
    alignItems: "center",
  },
  quickBody: {
    width: "100%",
    height: 110,
    backgroundColor: "white",
    marginTop: 10,
  },
  textDiv: {
    width: "100%",
    // justifyContent:'center',
    // alignItems:'center',
    borderBottomColor: "lightgrey",
    borderBottomWidth: 0.5,
    flexDirection: "row",
  },
  quickFooter: {
    width: "100%",
    height: 60,
    backgroundColor: "white",
    borderTopWidth: 0.5,
    borderTopColor: "lightgrey",
    // justifyContent:'center',
    // alignItems:'center'
    flexDirection: "row",
  },
  btnDiv: {
    width: "50%",
    height: 60,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  btnDiv2: {
    width: "50%",
    height: 60,
    backgroundColor: "white",
    borderLeftWidth: 0.5,
    borderLeftColor: "grey",
    justifyContent: "center",
    alignItems: "center",
  },
  separatorSection: {
    flexDirection: "column",
    alignItems: "center",
    width: width(0.2),
    height: 40,
    borderWidth: 0,
    backgroundColor: "lightgrey",
    marginTop: 10,
    marginBottom: 10,
  },
  dropdown: {
    height: 50,
    borderColor: 'gray',
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  icon: {
    marginRight: 5,
  },
  label: {
    position: 'absolute',
    backgroundColor: 'white',
    left: 22,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 14,
  },
  placeholderStyle: {
    fontSize: 16,
    color: 'grey'
  },
  selectedTextStyle: {
    fontSize: 16,
    color: 'grey'
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
});
