import { StyleSheet, Dimensions } from "react-native";
import { Metrics, ApplicationStyles } from "../../themes";
import Fonts from "../../themes/Fonts";
import { width, height } from "react-native-dimension";

let Window = Dimensions.get("window");

export default StyleSheet.create({
  ...ApplicationStyles.screen,
  fillcontainer: {
    flex: 1,
  },
  mainContainer: {
    flex: 1,
    width: Window.width,
    height: Window.height,
  },
  bgImage: {
    width: Window.width,
    height: "160%",
    resizeMode: "cover",
  },
  deliveryTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    // color: 'black',
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  deliveryTextStyle: {
    fontSize: Fonts.size.h4,
  },
  flatList: {
    width: "100%",
    height: "100%",
    //flex:4,
    //flexDirection:'column',
    position: "absolute",
    padding: 8,
    // marginTop: 60,
  },
  flatListView: {
    flex: 1,
    padding: 3,
  },
  flatListTouchableView: {
    width: "100%",
    flex: 4,
    borderRadius: 10,
    borderWidth: 0.1,
    elevation: 3,
    justifyContent: "center",
    alignItems: "flex-start",
    padding: 6,
    borderLeftColor: "green",
    flexDirection: "row",
  },
  buttonDiv: {
    width: "100%",
    justifyContent: "center",
    alignItems: "flex-start",
    flexDirection: "row",
  },
  parentBGColorOne: {
    backgroundColor: "transparent",
  },
  parentBGColorTwo: {
    // backgroundColor:'#d8d6ec',
    marginLeft: 5,
    width: Window.width - 28,
  },
  parentBGColorThree: {
    backgroundColor: "#d9efec",
    marginLeft: 10,
    width: Window.width - 32,
  },
  parentBGColorFour: {
    backgroundColor: "#ede6db",
    marginLeft: 15,
    width: Window.width - 37,
  },
  parentBGColorFive: {
    backgroundColor: "#ede6db",
    marginLeft: 20,
    width: Window.width - 42,
  },
  parentBGColorSix: {
    backgroundColor: "#ede6db",
    marginLeft: 25,
    width: Window.width - 47,
  },
  parentBGColorSeven: {
    backgroundColor: "#ede6db",
    marginLeft: 30,
    width: Window.width - 52,
  },
  listText: {
    color: "#AFAAAC",
    fontSize: Fonts.size.medium,
    padding: 5,
  },
  flatListInsideView: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 15,
  },
  deliveryTextNameStyle: {
    color: "white",
    fontSize: Fonts.size.input,
    width: "85%",
    fontWeight: "bold",
  },
  TextNameStyle: {
    color: "#00c7f9",
    fontSize: Fonts.size.input,
    width: "85%",
  },
  deliveryTypeTextStyle: {
    color: "white",
    fontSize: Fonts.size.medium,
    width: "85%",
  },
  TypeTextStyle: {
    color: "grey",
    fontSize: Fonts.size.medium,
    width: "85%",
  },
  apqpTextView: {
    flex: 1,
    width: Window.width,
    flexDirection: "row",
    //color:'black',
    position: "absolute",
    justifyContent: "space-between",
    alignItems: "center",
  },
  backLogo: {
    flexDirection: "row",
    backgroundColor: "transparent",
    width: width(15),
    height: 65,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTextDiv: {
    width: "80%",
    height: 70,
    justifyContent: "center",
    alignItems: "center",
  },
  apqpTextStyle: {
    fontSize: 24,
    color: "white",
  },

  DeliveryButton: {
    width: width(70),
    height: 40,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
  },
  DeliveryButton2: {
    width: width(70),
    height: 40,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    padding: 10,
    borderWidth: 1,
    borderColor: "#09578B",
  },
  buttonTextDel: {
    textAlign: "center",
    fontSize: Fonts.size.input,
    color: "white",
  },
  buttonText: {
    textAlign: "center",
    fontSize: Fonts.size.input,
  },
  progressVal: {
    fontSize: Fonts.size.medium,
    color: "#1d1d1d",
  },

  // projectButton: {
  //   width: width(7),
  //   height: 30,
  //   backgroundColor: "transparent",
  //   alignItems: "center",
  //   marginEnd:7,
  //   justifyContent: "center",
  // },

  projectIcon: {
    width: 20,
    height: 17,
    backgroundColor: "transparent",
    alignItems: "center",
    marginEnd: 7,
    justifyContent: "center",
  },

  modalStyle: {
    justifyContent: "flex-start",
    alignItems: "center",
    width: width(90),
    height: 220,
    backgroundColor: "white",
    borderRadius: 10,
    flexDirection: "column",
    // margin: 10,
    padding: 10,
    paddingBottom: 20,
  },
  makeSelectionText: {
    paddingLeft: 20,
    paddingBottom: 18,
    fontSize: Fonts.size.h5,
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  circleView: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    padding: 10,
    position: "absolute",
    right: 0,
    paddingLeft: 2,
  },
  progressVal: {
    fontSize: Fonts.size.medium,
    color: "#1d1d1d",
  },
  quickModaldiv: {
    width: "100%",
    height: 250,
    backgroundColor: "white",
    borderRadius: 5,
    padding: 10,
  },
  quickheader: {
    width: "100%",
    height: 60,
    backgroundColor: "white",
    borderBottomWidth: 0.5,
    borderBottomColor: "lightgrey",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  quickBody: {
    width: "100%",
    height: 110,
    backgroundColor: "white",
    marginTop: 10,
  },
  textDiv: {
    width: "100%",
    // justifyContent:'center',
    // alignItems:'center',
    borderBottomColor: "lightgrey",
    borderBottomWidth: 0.5,
    flexDirection: "row",
  },
  quickFooter: {
    width: "100%",
    height: 60,
    backgroundColor: "white",
    borderTopWidth: 0.5,
    borderTopColor: "lightgrey",
    // justifyContent:'center',
    // alignItems:'center'
    flexDirection: "row",
  },
  btnDiv: {
    width: "50%",
    height: 60,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  btnDiv2: {
    width: "50%",
    height: 60,
    backgroundColor: "white",
    borderLeftWidth: 0.5,
    borderLeftColor: "grey",
    justifyContent: "center",
    alignItems: "center",
  },
  roundView: {
    marginTop: 11,
    height: 20,
    width: 20,
    borderRadius: 20,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  header: {
    width: "100%",
    height: 50,
    alignItems: "center",
    flexDirection: "row",
  },
  headerDiv: {
    width: width(50),
    height: 65,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 25,
  },
  heading: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: width(70),
    height: 65,
  },
  headingText: {
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  LabelText: {
    paddingLeft: 5,
    fontSize: Fonts.size.h5,
    color: "#fff",
    textAlign: "center",
    fontFamily: "OpenSans-Bold",
  },
  fontText: {
    fontSize: 10,
    color: "grey",
  },
});
