// leave off @2x/@3x
const images = {
  logo: require("../../../Images/ir.png"),
  clearLogo: require("../../../Images/top_logo.png"),
  launch: require("../../../Images/launch-icon.png"),
  ready: require("../../../Images/your-app.png"),
  ignite: require("../../../Images/ignite_logo.png"),
  igniteClear: require("../../../Images/ignite-logo-transparent.png"),
  tileBg: require("../../../Images/tile_bg.png"),
  background: require("../../../Images/BG.png"),
  buttonBackground: require("../../../Images/button-bg.png"),
  api: require("../../../Images/Icons/icon-api-testing.png"),
  components: require("../../../Images/Icons/icon-components.png"),
  deviceInfo: require("../../../Images/Icons/icon-device-information.png"),
  faq: require("../../../Images/Icons/faq-icon.png"),
  home: require("../../../Images/Icons/icon-home.png"),
  theme: require("../../../Images/Icons/icon-theme.png"),
  usageExamples: require("../../../Images/Icons/icon-usage-examples.png"),
  chevronRight: require("../../../Images/Icons/chevron-right.png"),
  hamburger: require("../../../Images/Icons/hamburger.png"),
  backButton: require("../../../Images/Icons/back-button.png"),
  closeButton: require("../../../Images/Icons/close-button.png"),
  loginBack: require("../../../Images/LoginBack2.png"),
  topLogo: require("../../../Images/omnex_logo.png"),
  ologo: require("../../../Images/Ologo.png"),
  apqpLogo: require("../../../Images/APQP-PPAP.png"),
  loadingLogo: require("../../../Images/omnex_logo.png"),
  LoginBack: require("../../../Images/LoginBack.png"),
  humanLogo: require("../../../Images/bg_image1.png"),
  LockLogo: require("../../../Images/lock.png"),
  KeyLogo: require("../../../Images/key.png"),
  swipe: require("../../../Images/Swipe.png"),
  dashBack: require("../../../Images/Dashbg.png"),
  apqpwhitelogo: require("../../../Images/apqpwhitelogo.png"),
  dashbghalf: require("../../../Images/dashbghalf.png"),
  leftArrow: require("../../../Images/LeftArrow.png"),
  openIcons: require("../../../Images/open.png"),
  documentIcon: require("../../../Images/document.png"),
  inprogressIcon: require("../../../Images/inprogress.png"),
  meetingIcon: require("../../../Images/meeting.png"),
  riskIcon: require("../../../Images/risk.png"),
  apqpIcon: require("../../../Images/apqp.png"),

  apqpmanagerbg: require("../../../Images/bglayer_header.png"),
  footerImage: require("../../../Images/footer.png"),
  lineIcon: require("../../../Images/line_icon_white.png"),
  bglayer: require("../../../Images/bglayer.png"),
  headerBG: require("../../../Images/header.png"),

  apqpModuleIcon: require("../../../Images/apqp-icon.png"),
  riskModuleIcon: require("../../../Images/risk-icon.png"),
  meetingModuleIcon: require("../../../Images/meeting-icon.png"),
  publishIcon: require("../../../Images/icon_publish.png"),

  BGlayerFooter: require("../../../Images/bglayer_bottom.png"),
  refreshIcon: require("../../../Images/Icons/refresh.png"),
};

export default images;
